//! This crate contains a framework for low-degree tests (LDTs).

#![no_std]

mod naive;

pub use naive::*;

extern crate alloc;

use p3_field::{Field, TwoAdicField};
use p3_matrix::dense::RowMajorMatrix;

/// Computes low-degree extensions of polynomials over `F`, which are given in the Lagrange basis
/// over two-adic multiplicative subgroups of `FE`.
pub trait TwoAdicLDE<F, FE>
where
    F: Field,
    FE: Field<Base = F> + TwoAdicField,
{
    /// The result type. Typically this will be `FE`, but it may also be a compressed encoding of
    /// the subspace of `FE` that may be produced by LDEs.
    type Res: Into<FE>;

    /// Given a batch of polynomials, each defined by `2^k` evaluations over the subgroup generated
    /// by `F::primitive_root_of_unity(k)`, compute their evaluations over the subgroup generated
    /// by `F::primitive_root_of_unity(k + added_bits)`.
    fn subgroup_lde_batch(
        &self,
        polys: RowMajorMatrix<F>,
        added_bits: usize,
    ) -> RowMajorMatrix<Self::Res>;

    /// Given a batch of polynomials, each defined by `2^k` evaluations over the subgroup generated
    /// by `F::primitive_root_of_unity(k)`, compute their evaluations over the coset `shift H`,
    /// where `H` is the subgroup generated by `F::primitive_root_of_unity(k + added_bits)`.
    fn coset_lde_batch(
        &self,
        polys: RowMajorMatrix<F>,
        added_bits: usize,
        shift: FE,
    ) -> RowMajorMatrix<Self::Res>;
}
