//! Poseidon1 permutation for BabyBear.
//!
//! # MDS Matrix
//!
//! The MDS matrix is a **circulant** matrix sourced from the MDS crate.
//! At runtime, it is applied via fast Karatsuba convolution (sub-O(t^2)).
//! During initialization only, it is expanded to dense form for the
//! sparse matrix decomposition of partial rounds.
//!
//! # Round Constants
//!
//! Generated by the Grain LFSR (Poseidon1 paper, Appendix E) with SBOX=0 (x^alpha encoding).

use p3_monty_31::{
    GenericPoseidon1LinearLayersMonty31, MDSUtils, MdsMatrixMontyField31,
    PartialRoundBaseParameters, PartialRoundParameters, Poseidon1ExternalLayerMonty31,
    Poseidon1InternalLayerMonty31,
};
use p3_poseidon1::{Poseidon1, Poseidon1Constants};
use p3_symmetric::Permutation;

use crate::mds::MDSBabyBearData;
use crate::{BabyBear, BabyBearParameters};

/// Internal (partial round) layer for BabyBear Poseidon1.
pub type Poseidon1InternalLayerBabyBear<const WIDTH: usize> =
    Poseidon1InternalLayerMonty31<BabyBearParameters, WIDTH, BabyBearPoseidonParameters>;

/// External (full round) layer for BabyBear Poseidon1.
pub type Poseidon1ExternalLayerBabyBear<const WIDTH: usize> =
    Poseidon1ExternalLayerMonty31<BabyBearParameters, MDSBabyBearData, WIDTH>;

/// S-box degree for BabyBear Poseidon1.
///
/// Since `p - 1 = 15 * 2^27`, both 3 and 5 divide `p - 1`.
///
/// So `gcd(α, p - 1) ≠ 1` for `α ∈ {3, 5}`. The next smallest valid exponent is 7.
pub const BABYBEAR_S_BOX_DEGREE: u64 = 7;

/// Number of full rounds per half for BabyBear Poseidon1 (`RF / 2`).
///
/// The total number of full rounds is `RF = 8` (4 beginning + 4 ending).
/// Follows the Poseidon1 paper's security analysis (Section 5.4) with a +2 RF margin.
pub const BABYBEAR_POSEIDON1_HALF_FULL_ROUNDS: usize = 4;

/// Number of partial rounds for BabyBear Poseidon1 (width 16).
///
/// Derived from the Gröbner basis bound in the Poseidon1 paper (Eq. 4, line 2)
/// and the Poseidon2 paper (Eq. 1, R_GB term 3):
///
///   R_GB ≥ t − 7 + log_α(2) · min{κ/(t+1), log_2(p)/2}
///        = 9 + 0.3562 · min{7.53, 15.5} = 11.682
///
/// With the +7.5% security margin (Section 5.4): ⌈1.075 × 11.682⌉ = 13.
pub const BABYBEAR_POSEIDON1_PARTIAL_ROUNDS_16: usize = 13;

/// Number of partial rounds for BabyBear Poseidon1 (width 24).
///
/// Same Gröbner basis bound as width 16:
///
///   R_GB ≥ 17 + 0.3562 · min{5.12, 15.5} = 18.824
///
/// With the +7.5% security margin: ⌈1.075 × 18.824⌉ = 21.
pub const BABYBEAR_POSEIDON1_PARTIAL_ROUNDS_24: usize = 21;

/// The Poseidon1 permutation for BabyBear.
///
/// Acts on arrays of the form `[BabyBear; WIDTH]` or `[BabyBear::Packing; WIDTH]`.
pub type Poseidon1BabyBear<const WIDTH: usize> = Poseidon1<
    BabyBear,
    Poseidon1ExternalLayerBabyBear<WIDTH>,
    Poseidon1InternalLayerBabyBear<WIDTH>,
    WIDTH,
    BABYBEAR_S_BOX_DEGREE,
>;

/// Generic Poseidon1 linear layers for BabyBear.
///
/// Can act on `[A; WIDTH]` for any ring implementing `Algebra<BabyBear>`.
pub type GenericPoseidon1LinearLayersBabyBear =
    GenericPoseidon1LinearLayersMonty31<BabyBearParameters, BabyBearPoseidonParameters>;

/// Parameters for the Poseidon1 internal layer on BabyBear.
#[derive(Debug, Clone, Default)]
pub struct BabyBearPoseidonParameters;

impl PartialRoundBaseParameters<BabyBearParameters, 16> for BabyBearPoseidonParameters {
    const USE_TEXTBOOK: bool = true;

    fn mds_permute(state: &mut [BabyBear; 16]) {
        MdsMatrixMontyField31::<MDSBabyBearData>::default().permute_mut(state);
    }
}
impl PartialRoundBaseParameters<BabyBearParameters, 24> for BabyBearPoseidonParameters {}
impl PartialRoundParameters<BabyBearParameters, 16> for BabyBearPoseidonParameters {}
impl PartialRoundParameters<BabyBearParameters, 24> for BabyBearPoseidonParameters {}

/// Full round constants for width-16 Poseidon1 on BabyBear.
///
/// Generated by the Grain LFSR with parameters:
///     field_type=1, alpha=7 (exp_flag=0), n=31, t=16, R_F=8, R_P=13
///
/// Generated by `poseidon/generate_constants.py --field babybear --width 16`.
///
/// Layout: [initial_full (4 rounds), terminal_full (4 rounds)].
pub const BABYBEAR_POSEIDON1_FULL_RC_16: [[BabyBear; 16]; 8] = BabyBear::new_2d_array([
    // Initial full rounds (4)
    [
        0x69cbb6af, 0x46ad93f9, 0x60a00f4e, 0x6b1297cd, 0x23189afe, 0x732e7bef, 0x72c246de,
        0x2c941900, 0x0557eede, 0x1580496f, 0x3a3ea77b, 0x54f3f271, 0x0f49b029, 0x47872fe1,
        0x221e2e36, 0x1ab7202e,
    ],
    [
        0x487779a6, 0x3851c9d8, 0x38dc17c0, 0x209f8849, 0x268dcee8, 0x350c48da, 0x5b9ad32e,
        0x0523272b, 0x3f89055b, 0x01e894b2, 0x13ddedde, 0x1b2ef334, 0x7507d8b4, 0x6ceeb94e,
        0x52eb6ba2, 0x50642905,
    ],
    [
        0x05453f3f, 0x06349efc, 0x6922787c, 0x04bfff9c, 0x768c714a, 0x3e9ff21a, 0x15737c9c,
        0x2229c807, 0x0d47f88c, 0x097e0ecc, 0x27eadba0, 0x2d7d29e4, 0x3502aaa0, 0x0f475fd7,
        0x29fbda49, 0x018afffd,
    ],
    [
        0x0315b618, 0x6d4497d1, 0x1b171d9e, 0x52861abd, 0x2e5d0501, 0x3ec8646c, 0x6e5f250a,
        0x148ae8e6, 0x17f5fa4a, 0x3e66d284, 0x0051aa3b, 0x483f7913, 0x2cfe5f15, 0x023427ca,
        0x2cc78315, 0x1e36ea47,
    ],
    // Terminal full rounds (4)
    [
        0x366cb7ec, 0x0e6335de, 0x5e1374ca, 0x493cf6d2, 0x2ffe3703, 0x19dd3b51, 0x3d64878f,
        0x3ef43ee8, 0x64723e7c, 0x4fe5418a, 0x0f7b671d, 0x3f3adb8c, 0x1830fd89, 0x5b15366e,
        0x3ca9204d, 0x149cee3c,
    ],
    [
        0x547bb959, 0x4d6a44a0, 0x771612ca, 0x3f5bdd26, 0x23a3d984, 0x170b07bd, 0x5a2a5094,
        0x6e7e68b4, 0x1f3c8320, 0x0ffbb8b6, 0x5ebe7442, 0x45ffc700, 0x64d1f7b6, 0x1b30b661,
        0x586ea500, 0x503111fd,
    ],
    [
        0x72b41cf7, 0x6468ad65, 0x64c713b1, 0x450b1ccd, 0x211e6028, 0x300b11ac, 0x74226654,
        0x56308a44, 0x5aa55b4a, 0x52f2bc9a, 0x1a076e50, 0x5eb92894, 0x13baaf6f, 0x4d19b625,
        0x30d25297, 0x52f00c13,
    ],
    [
        0x2a6753d7, 0x40bdd8de, 0x22acbb98, 0x77e41654, 0x23ab6b0f, 0x0629e7d6, 0x000eadff,
        0x64cc8e81, 0x364fc012, 0x43cc48cd, 0x611baf29, 0x48bdf828, 0x1a8ab06f, 0x112ee5e0,
        0x036e01dc, 0x18106634,
    ],
]);

/// Partial round constants for width-16 Poseidon1 on BabyBear.
///
/// Generated by the Grain LFSR with parameters:
///     field_type=1, alpha=7 (exp_flag=0), n=31, t=16, R_F=8, R_P=13
///
/// Generated by `poseidon/generate_constants.py --field babybear --width 16`.
///
/// Contains only the first element of each partial round row (scalar S-box input).
pub const BABYBEAR_POSEIDON1_PARTIAL_RC_16: [BabyBear; 13] = BabyBear::new_array([
    0x5a8053c0, 0x76a859a0, 0x1448bc54, 0x0eba33ba, 0x1d7c2824, 0x1cb929e6, 0x16dd2e49, 0x0d8eacbc,
    0x27c99e66, 0x4b1392b6, 0x02d04b6d, 0x1d7cd264, 0x0f8b2954,
]);

/// Full round constants for width-24 Poseidon1 on BabyBear.
///
/// Generated by the Grain LFSR with parameters:
///     field_type=1, alpha=7 (exp_flag=0), n=31, t=24, R_F=8, R_P=21
///
/// Generated by `poseidon/generate_constants.py --field babybear --width 24`.
///
/// Layout: [initial_full (4 rounds), terminal_full (4 rounds)].
pub const BABYBEAR_POSEIDON1_FULL_RC_24: [[BabyBear; 24]; 8] = BabyBear::new_2d_array([
    // Initial full rounds (4)
    [
        0x0fa20c37, 0x0795bb97, 0x12c60b9c, 0x0eabd88e, 0x096485ca, 0x07093527, 0x1b1d4e50,
        0x30a01ace, 0x3bd86f5a, 0x69af7c28, 0x3f94775f, 0x731560e8, 0x465a0ecd, 0x574ef807,
        0x62fd4870, 0x52ccfe44, 0x14772b14, 0x4dedf371, 0x260acd7c, 0x1f51dc58, 0x75125532,
        0x686a4d7b, 0x54bac179, 0x31947706,
    ],
    [
        0x29799d3b, 0x6e01ae90, 0x203a7a64, 0x4f7e25be, 0x72503f77, 0x45bd3b69, 0x769bd6b4,
        0x5a867f08, 0x4fdba082, 0x251c4318, 0x28f06201, 0x6788c43a, 0x4c6d6a99, 0x357784a8,
        0x2abaf051, 0x770f7de6, 0x1794b784, 0x4796c57a, 0x724b7a10, 0x449989a7, 0x64935cf1,
        0x59e14aac, 0x0e620bb8, 0x3af5a33b,
    ],
    [
        0x4465cc0e, 0x019df68f, 0x4af8d068, 0x08784f82, 0x0cefdeae, 0x6337a467, 0x32fa7a16,
        0x486f62d6, 0x386a7480, 0x20f17c4a, 0x54e50da8, 0x2012cf03, 0x5fe52950, 0x09afb6cd,
        0x2523044e, 0x5c54d0ef, 0x71c01f3c, 0x60b2c4fb, 0x4050b379, 0x5e6a70a5, 0x418543f5,
        0x71debe56, 0x1aad2994, 0x3368a483,
    ],
    [
        0x07a86f3a, 0x5ea43ff1, 0x2443780e, 0x4ce444f7, 0x146f9882, 0x3132b089, 0x197ea856,
        0x667030c3, 0x2317d5dc, 0x0c2c48a7, 0x56b2df66, 0x67bd81e9, 0x4fcdfb19, 0x4baaef32,
        0x0328d30a, 0x6235760d, 0x12432912, 0x0a49e258, 0x030e1b70, 0x48caeb03, 0x49e4d9e9,
        0x1051b5c6, 0x6a36dbbe, 0x4cff27a5,
    ],
    // Terminal full rounds (4)
    [
        0x0fc4efce, 0x62ecb9d9, 0x33fd96c4, 0x69975a21, 0x1448aab1, 0x2021b32d, 0x02761f78,
        0x36d32b9a, 0x49f27e6b, 0x6b3c0905, 0x3ec37660, 0x294b9aef, 0x6f91b6ca, 0x72916b26,
        0x05f0a48a, 0x00625502, 0x15fdb305, 0x167d5214, 0x4679ee70, 0x746d93b3, 0x3df48789,
        0x4f5e66f6, 0x57100659, 0x6d511c3f,
    ],
    [
        0x41446816, 0x34a9a45e, 0x11789802, 0x0e6e7543, 0x3543a894, 0x271aa58f, 0x6c18fabe,
        0x6716e081, 0x4e7ebd9f, 0x6ac3f192, 0x5b81c87d, 0x4d5994fd, 0x0b1de23a, 0x57a1ab89,
        0x2d651a8f, 0x1cee7cf3, 0x2ebacc98, 0x0f627a88, 0x10df6935, 0x0e71678d, 0x34d4613a,
        0x677b1b3c, 0x47812824, 0x41c6a57e,
    ],
    [
        0x151419e4, 0x4f91c429, 0x5ef4f800, 0x666ef479, 0x32a1775a, 0x720ce960, 0x1e3f9af6,
        0x718d884d, 0x1a15cd27, 0x335d850c, 0x49c98fa3, 0x69cc0acb, 0x1cff3339, 0x5408e304,
        0x4e6e866e, 0x3be35d35, 0x3e1f2905, 0x23f1d80d, 0x662e279f, 0x1435e4a3, 0x75e2dd05,
        0x0988624a, 0x377a1b05, 0x7628ec95,
    ],
    [
        0x61010841, 0x42bbccb9, 0x078cfd5b, 0x494f7cbd, 0x67e80643, 0x29c7d710, 0x346f1642,
        0x5e50b089, 0x683a9d1c, 0x6d85d09f, 0x74c82186, 0x2a09cc00, 0x57035a44, 0x5851c292,
        0x032bf1f1, 0x29920074, 0x11b31845, 0x3a6424f5, 0x15d2972b, 0x3f3fcaf7, 0x03eb9631,
        0x67a5df9c, 0x6bb87fbf, 0x4ad8f8b6,
    ],
]);

/// Partial round constants for width-24 Poseidon1 on BabyBear.
///
/// Generated by the Grain LFSR with parameters:
///     field_type=1, alpha=7 (exp_flag=0), n=31, t=24, R_F=8, R_P=21
///
/// Generated by `poseidon/generate_constants.py --field babybear --width 24`.
///
/// Contains only the first element of each partial round row (scalar S-box input).
pub const BABYBEAR_POSEIDON1_PARTIAL_RC_24: [BabyBear; 21] = BabyBear::new_array([
    0x1da78ec2, 0x43bd26c8, 0x485762bb, 0x70c0192e, 0x2bfe636a, 0x28080606, 0x68dc180d, 0x124dede5,
    0x4d9dad01, 0x5cdef81e, 0x710937b7, 0x32e5b93a, 0x3a75137f, 0x474976a3, 0x5b4ea7fa, 0x1c4df5d1,
    0x122ae678, 0x0c959b6a, 0x7258f84d, 0x6e09a5ec, 0x0978f179,
]);

/// Create a default width-16 Poseidon1 permutation for BabyBear.
pub fn default_babybear_poseidon1_16() -> Poseidon1BabyBear<16> {
    Poseidon1::new(&Poseidon1Constants {
        rounds_f: 2 * BABYBEAR_POSEIDON1_HALF_FULL_ROUNDS,
        rounds_p: BABYBEAR_POSEIDON1_PARTIAL_ROUNDS_16,
        mds_circ_col: MDSBabyBearData::MATRIX_CIRC_MDS_16_COL,
        full_round_constants: BABYBEAR_POSEIDON1_FULL_RC_16.to_vec(),
        partial_round_constants: BABYBEAR_POSEIDON1_PARTIAL_RC_16.to_vec(),
    })
}

/// Create a default width-24 Poseidon1 permutation for BabyBear.
pub fn default_babybear_poseidon1_24() -> Poseidon1BabyBear<24> {
    Poseidon1::new(&Poseidon1Constants {
        rounds_f: 2 * BABYBEAR_POSEIDON1_HALF_FULL_ROUNDS,
        rounds_p: BABYBEAR_POSEIDON1_PARTIAL_ROUNDS_24,
        mds_circ_col: MDSBabyBearData::MATRIX_CIRC_MDS_24_COL,
        full_round_constants: BABYBEAR_POSEIDON1_FULL_RC_24.to_vec(),
        partial_round_constants: BABYBEAR_POSEIDON1_PARTIAL_RC_24.to_vec(),
    })
}

#[cfg(test)]
mod tests {
    use p3_symmetric::Permutation;

    use super::*;

    type F = BabyBear;

    #[test]
    fn test_poseidon_width_16() {
        let perm = default_babybear_poseidon1_16();

        let mut input: [F; 16] =
            F::new_array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]);

        let expected: [F; 16] = F::new_array([
            0x03a07919, 0x5401da41, 0x1372ba47, 0x1831642f, 0x1bea267a, 0x3dbe043b, 0x672ca057,
            0x74b26137, 0x2657d79f, 0x49299ae8, 0x7551ce46, 0x630e918f, 0x00680229, 0x74bdf7aa,
            0x6e9e62ea, 0x2d465709,
        ]);

        perm.permute_mut(&mut input);
        assert_eq!(input, expected);
    }

    #[test]
    fn test_poseidon_width_24() {
        let perm = default_babybear_poseidon1_24();

        let mut input: [F; 24] = F::new_array([
            0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
        ]);

        let expected: [F; 24] = F::new_array([
            0x448637b6, 0x157a14d3, 0x15165210, 0x2f6a4f34, 0x4f48335a, 0x14584d64, 0x09f6ed0c,
            0x1b1f0e91, 0x46b1345b, 0x4364374a, 0x15c95d9f, 0x52d1c3c3, 0x4bd29498, 0x316b6aca,
            0x152e9447, 0x5bdd1fa7, 0x2ba9cc63, 0x3007283e, 0x2869b888, 0x65b67fec, 0x1f01f753,
            0x15dd450c, 0x314f8646, 0x2bf60a25,
        ]);

        perm.permute_mut(&mut input);
        assert_eq!(input, expected);
    }
}
