

# This file was *autogenerated* from the file poseidon1_babybear.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2013265921 = Integer(2013265921); _sage_const_16 = Integer(16); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_500 = Integer(500); _sage_const_4 = Integer(4); _sage_const_100 = Integer(100); _sage_const_1p075 = RealNumber('1.075'); _sage_const_6 = Integer(6); _sage_const_2p0 = RealNumber('2.0'); _sage_const_10 = Integer(10); _sage_const_3p0 = RealNumber('3.0'); _sage_const_128 = Integer(128); _sage_const_160 = Integer(160); _sage_const_62 = Integer(62); _sage_const_51 = Integer(51); _sage_const_38 = Integer(38); _sage_const_23 = Integer(23); _sage_const_13 = Integer(13); _sage_const_12 = Integer(12); _sage_const_30 = Integer(30)# Poseidon1 constants for BabyBear (p = 2013265921)
# Usage: sage poseidon1_babybear.sage
# Change t below for different widths (16 for compression, 24 for sponge)
from sage.rings.polynomial.polynomial_gf2x import GF2X_BuildIrred_list
from math import *
import itertools

###########################################################################
p = _sage_const_2013265921  # BabyBear

n = len(p.bits()) # bit
t = _sage_const_16  # BabyBear (t = 24 for sponge, t = 16 for compression)

FIELD = _sage_const_1 
SBOX = _sage_const_0 
FIELD_SIZE = n
NUM_CELLS = t

def get_alpha(p):
    for alpha in range(_sage_const_3 , p):
        if gcd(alpha, p-_sage_const_1 ) == _sage_const_1 :
            break
    return alpha

alpha = get_alpha(p)

def get_sbox_cost(R_F, R_P, N, t):
    return int(t * R_F + R_P)

def get_size_cost(R_F, R_P, N, t):
    n = ceil(float(N) / t)
    return int((N * R_F) + (n * R_P))

def poseidon_calc_final_numbers_fixed(p, t, alpha, M, security_margin):
    n = ceil(log(p, _sage_const_2 ))
    N = int(n * t)
    cost_function = get_sbox_cost
    ret_list = []
    (R_F, R_P) = find_FD_round_numbers(p, t, alpha, M, cost_function, security_margin)
    min_sbox_cost = cost_function(R_F, R_P, N, t)
    ret_list.append(R_F)
    ret_list.append(R_P)
    ret_list.append(min_sbox_cost)
    min_size_cost = get_size_cost(R_F, R_P, N, t)
    ret_list.append(min_size_cost)
    return ret_list

def find_FD_round_numbers(p, t, alpha, M, cost_function, security_margin):
    n = ceil(log(p, _sage_const_2 ))
    N = int(n * t)
    sat_inequiv = sat_inequiv_alpha
    R_P = _sage_const_0 
    R_F = _sage_const_0 
    min_cost = float("inf")
    max_cost_rf = _sage_const_0 
    for R_P_t in range(_sage_const_1 , _sage_const_500 ):
        for R_F_t in range(_sage_const_4 , _sage_const_100 ):
            if R_F_t % _sage_const_2  == _sage_const_0 :
                if (sat_inequiv(p, t, R_F_t, R_P_t, alpha, M) == True):
                    if security_margin == True:
                        R_F_t += _sage_const_2 
                        R_P_t = int(ceil(float(R_P_t) * _sage_const_1p075 ))
                    cost = cost_function(R_F_t, R_P_t, N, t)
                    if (cost < min_cost) or ((cost == min_cost) and (R_F_t < max_cost_rf)):
                        R_P = ceil(R_P_t)
                        R_F = ceil(R_F_t)
                        min_cost = cost
                        max_cost_rf = R_F
    return (int(R_F), int(R_P))

def sat_inequiv_alpha(p, t, R_F, R_P, alpha, M):
    N = int(FIELD_SIZE * NUM_CELLS)
    if alpha > _sage_const_0 :
        R_F_1 = _sage_const_6  if M <= ((floor(log(p, _sage_const_2 ) - ((alpha-_sage_const_1 )/_sage_const_2p0 ))) * (t + _sage_const_1 )) else _sage_const_10 
        R_F_2 = _sage_const_1  + ceil(log(_sage_const_2 , alpha) * min(M, FIELD_SIZE)) + ceil(log(t, alpha)) - R_P
        R_F_3 = (log(_sage_const_2 , alpha) * min(M, log(p, _sage_const_2 ))) - R_P
        R_F_4 = t - _sage_const_1  + log(_sage_const_2 , alpha) * min(M / float(t + _sage_const_1 ), log(p, _sage_const_2 ) / float(_sage_const_2 )) - R_P
        R_F_5 = (t - _sage_const_2  + (M / float(_sage_const_2  * log(alpha, _sage_const_2 ))) - R_P) / float(t - _sage_const_1 )
        R_F_max = max(ceil(R_F_1), ceil(R_F_2), ceil(R_F_3), ceil(R_F_4), ceil(R_F_5))
        r_temp = floor(t / _sage_const_3p0 )
        over = (R_F - _sage_const_1 ) * t + R_P + r_temp + r_temp * (R_F / _sage_const_2p0 ) + R_P + alpha
        under = r_temp * (R_F / _sage_const_2p0 ) + R_P + alpha
        binom_log = log(binomial(over, under), _sage_const_2 )
        if binom_log == inf:
            binom_log = M + _sage_const_1 
        cost_gb4 = ceil(_sage_const_2  * binom_log)
        return ((R_F >= R_F_max) and (cost_gb4 >= M))
    else:
        print("Invalid value for alpha!")
        exit(_sage_const_1 )

R_F_FIXED, R_P_FIXED, _, _ = poseidon_calc_final_numbers_fixed(p, t, alpha, _sage_const_128 , True)
print("+++ R_F = {0}, R_P = {1} +++".format(R_F_FIXED, R_P_FIXED))

###########################################################################

INIT_SEQUENCE = []
PRIME_NUMBER = p
F = GF(PRIME_NUMBER)

def grain_sr_generator():
    bit_sequence = INIT_SEQUENCE
    for _ in range(_sage_const_0 , _sage_const_160 ):
        new_bit = bit_sequence[_sage_const_62 ] ^ bit_sequence[_sage_const_51 ] ^ bit_sequence[_sage_const_38 ] ^ bit_sequence[_sage_const_23 ] ^ bit_sequence[_sage_const_13 ] ^ bit_sequence[_sage_const_0 ]
        bit_sequence.pop(_sage_const_0 )
        bit_sequence.append(new_bit)
    while True:
        new_bit = bit_sequence[_sage_const_62 ] ^ bit_sequence[_sage_const_51 ] ^ bit_sequence[_sage_const_38 ] ^ bit_sequence[_sage_const_23 ] ^ bit_sequence[_sage_const_13 ] ^ bit_sequence[_sage_const_0 ]
        bit_sequence.pop(_sage_const_0 )
        bit_sequence.append(new_bit)
        while new_bit == _sage_const_0 :
            new_bit = bit_sequence[_sage_const_62 ] ^ bit_sequence[_sage_const_51 ] ^ bit_sequence[_sage_const_38 ] ^ bit_sequence[_sage_const_23 ] ^ bit_sequence[_sage_const_13 ] ^ bit_sequence[_sage_const_0 ]
            bit_sequence.pop(_sage_const_0 )
            bit_sequence.append(new_bit)
            new_bit = bit_sequence[_sage_const_62 ] ^ bit_sequence[_sage_const_51 ] ^ bit_sequence[_sage_const_38 ] ^ bit_sequence[_sage_const_23 ] ^ bit_sequence[_sage_const_13 ] ^ bit_sequence[_sage_const_0 ]
            bit_sequence.pop(_sage_const_0 )
            bit_sequence.append(new_bit)
        new_bit = bit_sequence[_sage_const_62 ] ^ bit_sequence[_sage_const_51 ] ^ bit_sequence[_sage_const_38 ] ^ bit_sequence[_sage_const_23 ] ^ bit_sequence[_sage_const_13 ] ^ bit_sequence[_sage_const_0 ]
        bit_sequence.pop(_sage_const_0 )
        bit_sequence.append(new_bit)
        yield new_bit
grain_gen = grain_sr_generator()

def grain_random_bits(num_bits):
    random_bits = [next(grain_gen) for i in range(_sage_const_0 , num_bits)]
    random_int = int("".join(str(i) for i in random_bits), _sage_const_2 )
    return random_int

def init_generator(field, sbox, n, t, R_F, R_P):
    bit_list_field = [_ for _ in (bin(FIELD)[_sage_const_2 :].zfill(_sage_const_2 ))]
    bit_list_sbox = [_ for _ in (bin(SBOX)[_sage_const_2 :].zfill(_sage_const_4 ))]
    bit_list_n = [_ for _ in (bin(FIELD_SIZE)[_sage_const_2 :].zfill(_sage_const_12 ))]
    bit_list_t = [_ for _ in (bin(NUM_CELLS)[_sage_const_2 :].zfill(_sage_const_12 ))]
    bit_list_R_F = [_ for _ in (bin(R_F)[_sage_const_2 :].zfill(_sage_const_10 ))]
    bit_list_R_P = [_ for _ in (bin(R_P)[_sage_const_2 :].zfill(_sage_const_10 ))]
    bit_list_1 = [_sage_const_1 ] * _sage_const_30 
    global INIT_SEQUENCE
    INIT_SEQUENCE = bit_list_field + bit_list_sbox + bit_list_n + bit_list_t + bit_list_R_F + bit_list_R_P + bit_list_1
    INIT_SEQUENCE = [int(_) for _ in INIT_SEQUENCE]

def generate_constants(field, n, t, R_F, R_P, prime_number):
    round_constants = []
    num_constants = (R_F + R_P) * t # Poseidon1
    if field == _sage_const_0 :
        for i in range(_sage_const_0 , num_constants):
            random_int = grain_random_bits(n)
            round_constants.append(random_int)
    elif field == _sage_const_1 :
        for i in range(_sage_const_0 , num_constants):
            random_int = grain_random_bits(n)
            while random_int >= prime_number:
                random_int = grain_random_bits(n)
            round_constants.append(random_int)
    return round_constants

def create_mds_p(n, t):
    M = matrix(F, t, t)
    while True:
        flag = True
        rand_list = [F(grain_random_bits(n)) for _ in range(_sage_const_0 , _sage_const_2 *t)]
        while len(rand_list) != len(set(rand_list)):
            rand_list = [F(grain_random_bits(n)) for _ in range(_sage_const_0 , _sage_const_2 *t)]
        xs = rand_list[:t]
        ys = rand_list[t:]
        for i in range(_sage_const_0 , t):
            for j in range(_sage_const_0 , t):
                if (flag == False) or ((xs[i] + ys[j]) == _sage_const_0 ):
                    flag = False
                else:
                    entry = (xs[i] + ys[j])**(-_sage_const_1 )
                    M[i, j] = entry
        if flag == False:
            continue
        return M

def generate_vectorspace(round_num, M, M_round, NUM_CELLS):
    t = NUM_CELLS
    s = _sage_const_1 
    V = VectorSpace(F, t)
    if round_num == _sage_const_0 :
        return V
    elif round_num == _sage_const_1 :
        return V.subspace(V.basis()[s:])
    else:
        mat_temp = matrix(F)
        for i in range(_sage_const_0 , round_num-_sage_const_1 ):
            add_rows = []
            for j in range(_sage_const_0 , s):
                add_rows.append(M_round[i].rows()[j][s:])
            mat_temp = matrix(mat_temp.rows() + add_rows)
        r_k = mat_temp.right_kernel()
        extended_basis_vectors = []
        for vec in r_k.basis():
            extended_basis_vectors.append(vector([_sage_const_0 ]*s + list(vec)))
        S = V.subspace(extended_basis_vectors)
        return S

def subspace_times_matrix(subspace, M, NUM_CELLS):
    t = NUM_CELLS
    V = VectorSpace(F, t)
    subspace_basis = subspace.basis()
    new_basis = []
    for vec in subspace_basis:
        new_basis.append(M * vec)
    new_subspace = V.subspace(new_basis)
    return new_subspace

def algorithm_1(M, NUM_CELLS):
    t = NUM_CELLS
    s = _sage_const_1 
    r = floor((t - s) / float(s))
    M_round = []
    for j in range(_sage_const_0 , t+_sage_const_1 ):
        M_round.append(M**(j+_sage_const_1 ))
    for i in range(_sage_const_1 , r+_sage_const_1 ):
        mat_test = M**i
        entry = mat_test[_sage_const_0 , _sage_const_0 ]
        mat_target = matrix.circulant(vector([entry] + ([F(_sage_const_0 )] * (t-_sage_const_1 ))))
        if (mat_test - mat_target) == matrix.circulant(vector([F(_sage_const_0 )] * (t))):
            return [False, _sage_const_1 ]
        S = generate_vectorspace(i, M, M_round, t)
        V = VectorSpace(F, t)
        basis_vectors= []
        for eigenspace in mat_test.eigenspaces_right(format='galois'):
            if (eigenspace[_sage_const_0 ] not in F):
                continue
            vector_subspace = eigenspace[_sage_const_1 ]
            intersection = S.intersection(vector_subspace)
            basis_vectors += intersection.basis()
        IS = V.subspace(basis_vectors)
        if IS.dimension() >= _sage_const_1  and IS != V:
            return [False, _sage_const_2 ]
        for j in range(_sage_const_1 , i+_sage_const_1 ):
            S_mat_mul = subspace_times_matrix(S, M**j, t)
            if S == S_mat_mul:
                return [False, _sage_const_3 ]
    return [True, _sage_const_0 ]

def algorithm_2(M, NUM_CELLS):
    t = NUM_CELLS
    s = _sage_const_1 
    V = VectorSpace(F, t)
    trail = [None, None]
    test_next = False
    I = range(_sage_const_0 , s)
    I_powerset = list(sage.misc.misc.powerset(I))[_sage_const_1 :]
    for I_s in I_powerset:
        test_next = False
        new_basis = []
        for l in I_s:
            new_basis.append(V.basis()[l])
        IS = V.subspace(new_basis)
        for i in range(s, t):
            new_basis.append(V.basis()[i])
        full_iota_space = V.subspace(new_basis)
        for l in I_s:
            v = V.basis()[l]
            while True:
                delta = IS.dimension()
                v = M * v
                IS = V.subspace(IS.basis() + [v])
                if IS.dimension() == t or IS.intersection(full_iota_space) != IS:
                    test_next = True
                    break
                if IS.dimension() <= delta:
                    break
            if test_next == True:
                break
        if test_next == True:
            continue
        return [False, [IS, I_s]]
    return [True, None]

def algorithm_3(M, NUM_CELLS):
    t = NUM_CELLS
    s = _sage_const_1 
    V = VectorSpace(F, t)
    l = _sage_const_4 *t
    for r in range(_sage_const_2 , l+_sage_const_1 ):
        next_r = False
        res_alg_2 = algorithm_2(M**r, t)
        if res_alg_2[_sage_const_0 ] == False:
            return [False, None]
    return [True, None]

def generate_matrix(FIELD, FIELD_SIZE, NUM_CELLS):
    if FIELD == _sage_const_0 :
        print("Matrix generation not implemented for GF(2^n).")
        exit(_sage_const_1 )
    elif FIELD == _sage_const_1 :
        mds_matrix = create_mds_p(FIELD_SIZE, NUM_CELLS)
        result_1 = algorithm_1(mds_matrix, NUM_CELLS)
        result_2 = algorithm_2(mds_matrix, NUM_CELLS)
        result_3 = algorithm_3(mds_matrix, NUM_CELLS)
        while result_1[_sage_const_0 ] == False or result_2[_sage_const_0 ] == False or result_3[_sage_const_0 ] == False:
            mds_matrix = create_mds_p(FIELD_SIZE, NUM_CELLS)
            result_1 = algorithm_1(mds_matrix, NUM_CELLS)
            result_2 = algorithm_2(mds_matrix, NUM_CELLS)
            result_3 = algorithm_3(mds_matrix, NUM_CELLS)
        return mds_matrix

def poseidon(input_words, matrix, round_constants):
    R_f = int(R_F_FIXED / _sage_const_2 )
    round_constants_counter = _sage_const_0 
    state_words = list(input_words)
    for r in range(_sage_const_0 , R_f):
        for i in range(_sage_const_0 , t):
            state_words[i] = state_words[i] + round_constants[round_constants_counter]
            round_constants_counter += _sage_const_1 
        for i in range(_sage_const_0 , t):
            state_words[i] = (state_words[i])**alpha
        state_words = list(matrix * vector(state_words))
    for r in range(_sage_const_0 , R_P_FIXED):
        for i in range(_sage_const_0 , t):
            state_words[i] = state_words[i] + round_constants[round_constants_counter]
            round_constants_counter += _sage_const_1 
        state_words[_sage_const_0 ] = (state_words[_sage_const_0 ])**alpha
        state_words = list(matrix * vector(state_words))
    for r in range(_sage_const_0 , R_f):
        for i in range(_sage_const_0 , t):
            state_words[i] = state_words[i] + round_constants[round_constants_counter]
            round_constants_counter += _sage_const_1 
        for i in range(_sage_const_0 , t):
            state_words[i] = (state_words[i])**alpha
        state_words = list(matrix * vector(state_words))
    return state_words

# Init
init_generator(FIELD, SBOX, FIELD_SIZE, NUM_CELLS, R_F_FIXED, R_P_FIXED)

# Round constants
round_constants = generate_constants(FIELD, FIELD_SIZE, NUM_CELLS, R_F_FIXED, R_P_FIXED, PRIME_NUMBER)

# Matrix
MDS = generate_matrix(FIELD, FIELD_SIZE, NUM_CELLS)

# Output
hex_length = int(ceil(float(n) / _sage_const_4 )) + _sage_const_2 
print("MDS matrix:")
for i in range(_sage_const_0 , t):
    print(["{0:#0{1}x}".format(int(entry), hex_length) for entry in MDS[i]])
print()

print("Round constants (per round, {} elements each):".format(t))
print("Number of round constants:", len(round_constants))
for r in range(_sage_const_0 , R_F_FIXED + R_P_FIXED):
    rc_round = round_constants[r*t:(r+_sage_const_1 )*t]
    print("Round {}: {}".format(r, ["{0:#0{1}x}".format(entry, hex_length) for entry in rc_round]))
print()

state_in = vector([F(i) for i in range(t)])
state_out = poseidon(state_in, MDS, round_constants)
print("Input:  {}".format(["{0:#0{1}x}".format(int(val), hex_length) for val in state_in]))
print("Output: {}".format(["{0:#0{1}x}".format(int(val), hex_length) for val in state_out]))

