use crate::{LinearZkEncoding, ZkEncoding, ZkEncodingWithRandomness};
use alloc::vec::Vec;
use core::marker::PhantomData;
use p3_dft::TwoAdicSubgroupDft;
use p3_field::TwoAdicField;
use p3_matrix::Matrix;
use p3_matrix::dense::RowMajorMatrix;
use rand::{
    Rng, RngExt,
    distr::{Distribution, StandardUniform},
};

/// A Reed-Solomon zero-knowledge encoding.
///
/// Proposition 3.19 of eprint 2026/391.
///
/// Let `l` be the message length.
/// Let `t` be the required zero-knowledge bound.
/// Let `m` be the codeword length.
///
/// The encoding maps a message `f ∈ F^l` and randomness `r ∈ F^t` into `F^m`.
/// The polynomial is constructed with the message in the lower `l` degrees.
/// The random masks occupy the `t` degrees directly following them.
///
/// # Math
///
/// ```text
///     p_{f,r}(X) = (f_0 + … + f_{l-1} X^{l-1}) + (r_0 X^l + … + r_{t-1} X^{l+t-1})
/// ```
///
/// The codeword is the evaluation of `p_{f,r}(X)` over a subgroup of `F` of size `m`.
///
/// ```text
///     Enc_C(f, r) = (p_{f,r}(x_0), …, p_{f,r}(x_{m-1}))
/// ```
///
/// `x_i` are the roots of unity generated by the subgroup.
#[derive(Clone)]
pub struct ReedSolomonZkEncoding<F, Dft> {
    /// Number of codeword positions that reveal nothing about the message.
    pub t: usize,
    /// The message length.
    pub msg_len: usize,
    /// The codeword length.
    pub m: usize,
    /// The discrete Fourier transform implementation.
    pub dft: Dft,
    pub _phantom: PhantomData<F>,
}

impl<F: TwoAdicField, Dft> ReedSolomonZkEncoding<F, Dft> {
    pub const fn new(t: usize, msg_len: usize, m: usize, dft: Dft) -> Self {
        Self {
            t,
            msg_len,
            m,
            dft,
            _phantom: PhantomData,
        }
    }

    /// Retrieve the evaluation point `x` at the given index in the DFT domain.
    pub fn evaluation_point(&self, position: usize) -> F {
        let log2_m = self.m.trailing_zeros() as usize;
        let g = F::two_adic_generator(log2_m);
        g.exp_u64(position as u64)
    }
}

impl<F, Dft> ZkEncoding<F> for ReedSolomonZkEncoding<F, Dft>
where
    F: TwoAdicField,
    Dft: TwoAdicSubgroupDft<F>,
    StandardUniform: Distribution<F>,
{
    type Codeword = RowMajorMatrix<F>;

    fn message_len(&self) -> usize {
        self.msg_len
    }

    fn randomness_len(&self) -> usize {
        self.t
    }

    fn error(&self) -> f64 {
        0.0 // Reed-Solomon encoding provides perfect zero-knowledge (0 error).
    }

    fn encode<R: Rng>(&self, msg: &[F], rng: &mut R) -> Self::Codeword {
        let randomness: Vec<F> = (0..self.t).map(|_| rng.random::<F>()).collect();
        self.encode_with_randomness(msg, &randomness)
    }

    fn simulate<R: Rng>(&self, query_set: &[usize], rng: &mut R) -> Vec<F> {
        assert!(
            query_set.len() <= self.t,
            "Cannot simulate more than t queries"
        );
        // Any subset of size <= t evaluates to completely uniform randomness.
        (0..query_set.len()).map(|_| rng.random::<F>()).collect()
    }
}

impl<F, Dft> ZkEncodingWithRandomness<F> for ReedSolomonZkEncoding<F, Dft>
where
    F: TwoAdicField,
    Dft: TwoAdicSubgroupDft<F>,
    StandardUniform: Distribution<F>,
{
    fn encode_with_randomness(&self, msg: &[F], randomness: &[F]) -> Self::Codeword {
        assert_eq!(
            msg.len(),
            self.msg_len,
            "Message length must match configured msg_len"
        );
        assert_eq!(
            randomness.len(),
            self.t,
            "Randomness length must match configured t"
        );
        assert!(
            self.msg_len + self.t <= self.m,
            "Message and randomness exceed codeword length"
        );
        let mut coeffs = Vec::with_capacity(self.m);
        coeffs.extend_from_slice(msg);
        coeffs.extend_from_slice(randomness);
        coeffs.resize(self.m, F::ZERO);
        let mat = RowMajorMatrix::new_col(coeffs);
        self.dft.dft_batch(mat).to_row_major_matrix()
    }
}

impl<F, Dft> LinearZkEncoding<F> for ReedSolomonZkEncoding<F, Dft>
where
    F: TwoAdicField,
    Dft: TwoAdicSubgroupDft<F>,
    StandardUniform: Distribution<F>,
{
    /// Evaluates the message segment of the generator polynomial at the given evaluation point.
    ///
    /// Definition 3.17 of eprint 2026/391.
    ///
    /// `G_C` is decomposed into `[G^#_C | G^$_C]`.
    /// This extracts the row of `G^#_C` at index `i`.
    ///
    /// # Math
    ///
    /// ```text
    ///     G^#[i, *] = (1, x_i, x_i^2, …, x_i^{l-1})
    /// ```
    ///
    /// `l` is the message length and `x_i` is the evaluation point.
    fn message_row(&self, position: usize) -> Vec<F> {
        let x = self.evaluation_point(position);
        x.powers().take(self.msg_len).collect()
    }

    /// Evaluates the randomness (mask) segment of the generator polynomial.
    ///
    /// Definition 3.17 of eprint 2026/391.
    ///
    /// `G_C` is decomposed into `[G^#_C | G^$_C]`.
    /// This extracts the row of `G^$_C` at index `i`.
    ///
    /// # Math
    ///
    /// ```text
    ///     G^$[i, *] = (x_i^l, x_i^{l+1}, …, x_i^{l+t-1})
    /// ```
    ///
    /// `l` is the message length, `t` is the random bound, and `x_i` is the evaluation point.
    fn randomness_row(&self, position: usize) -> Vec<F> {
        let x = self.evaluation_point(position);
        let mut pow = x.exp_u64(self.msg_len as u64);
        let mut row = Vec::with_capacity(self.t);
        for _ in 0..self.t {
            row.push(pow);
            pow *= x;
        }
        row
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use alloc::vec;
    use p3_baby_bear::BabyBear;
    use p3_dft::Radix2Dit;
    use p3_field::PrimeCharacteristicRing;
    use proptest::prelude::*;
    use rand::SeedableRng;
    use rand_xoshiro::Xoshiro256PlusPlus;

    #[test]
    fn test_zero_randomness_matches_plain_rs() {
        let msg_len = 4;
        let t = 2;
        let m = 8;
        let dft = Radix2Dit::default();
        let encoding = ReedSolomonZkEncoding::<BabyBear, _>::new(t, msg_len, m, dft.clone());

        let msg = vec![
            BabyBear::new(1),
            BabyBear::new(2),
            BabyBear::new(3),
            BabyBear::new(4),
        ];

        // Eval with zero randomness.
        let encoded = encoding.encode_with_randomness(&msg, &vec![BabyBear::ZERO; t]);

        // Plain RS encodes by padding the message with zeros.
        let mut plain_coeffs = msg;
        plain_coeffs.resize(m, BabyBear::ZERO);
        let plain_mat = RowMajorMatrix::new_col(plain_coeffs);
        let plain_encoded = dft.dft_batch(plain_mat).to_row_major_matrix();

        assert_eq!(encoded.values, plain_encoded.values);
    }

    proptest! {
        #[test]
        fn test_simulate_distribution(seed in any::<u64>(), msg_seed in any::<u64>()) {
            let msg_len = 2;
            let t = 2;
            let m = 4;
            let dft = Radix2Dit::default();
            let encoding = ReedSolomonZkEncoding::<BabyBear, _>::new(t, msg_len, m, dft);

            let mut msg_rng = Xoshiro256PlusPlus::seed_from_u64(msg_seed);
            let msg = vec![msg_rng.random::<BabyBear>(), msg_rng.random::<BabyBear>()];

            let mut rng1 = Xoshiro256PlusPlus::seed_from_u64(seed);
            let _encoded = encoding.encode(&msg, &mut rng1);

            let mut rng2 = Xoshiro256PlusPlus::seed_from_u64(seed);
            let simulated = encoding.simulate(&[0, 1], &mut rng2);

            // Any subset size <= t matches the theoretical uniform distribution.
            assert_eq!(simulated.len(), 2);
        }
    }

    #[test]
    fn test_row_decomposition() {
        let t = 2;
        let msg_len = 2;
        let m = 8;
        let dft = Radix2Dit::default();
        let encoding = ReedSolomonZkEncoding::<BabyBear, _>::new(t, msg_len, m, dft);

        let msg = vec![BabyBear::new(3), BabyBear::new(5)];
        let mut rng = Xoshiro256PlusPlus::seed_from_u64(42);

        // Capture randomness for manual evaluation.
        let rand_values: Vec<BabyBear> = (0..t).map(|_| rng.random()).collect();

        // Encode using the identical randomness.
        let encoded = encoding.encode_with_randomness(&msg, &rand_values).values;

        // Verify Enc(f, r)[i] = G#[i] * f + G$[i] * r.
        for (i, &enc_val) in encoded.iter().enumerate().take(m) {
            let msg_row = encoding.message_row(i);
            let rand_row = encoding.randomness_row(i);

            let msg_dot: BabyBear = msg_row.iter().zip(&msg).map(|(a, b)| *a * *b).sum();
            let rand_dot: BabyBear = rand_row
                .iter()
                .zip(&rand_values)
                .map(|(a, b)| *a * *b)
                .sum();

            assert_eq!(enc_val, msg_dot + rand_dot);
        }
    }
}
