use crate::{LinearZkEncoding, ZkEncoding, ZkEncodingWithRandomness};
use alloc::vec::Vec;
use core::marker::PhantomData;
use p3_dft::TwoAdicSubgroupDft;
use p3_field::TwoAdicField;
use p3_matrix::Matrix;
use p3_matrix::dense::RowMajorMatrix;
use rand::{
    Rng, RngExt,
    distr::{Distribution, StandardUniform},
};

/// A Reed-Solomon zero-knowledge encoding.
///
/// As described in eprint 2026/391, Proposition 3.19 (Zero-Knowledge Reed-Solomon Code):
/// Let ℓ be the message length (`msg_len`), t be the required zero-knowledge bound (`t`),
/// and m be the codeword length (`m`).
///
/// The encoding maps a message vector f ∈ F^ℓ and a randomness vector r ∈ F^t into a codeword in F^m.
/// Mathematically, a polynomial is constructed such that the message coefficients occupy the lower
/// ℓ degrees, and the random masks occupy the t degrees directly following them:
///
/// p_f,r(X) = (f_0 + f_1 X + ... + f_{ℓ-1} X^{ℓ-1}) + (r_0 X^ℓ + ... + r_{t-1} X^{ℓ+t-1})
///
/// The final codeword is the evaluation of p_f,r(X) over a subgroup of F of size m:
/// Enc_C(f, r) = ( p_f,r(x_0), p_f,r(x_1), ..., p_f,r(x_{m-1}) )
/// where x_i are the roots of unity generated by the subgroup.
#[derive(Clone)]
pub struct ReedSolomonZkEncoding<F, Dft> {
    /// Number of codeword positions that reveal nothing about the message.
    pub t: usize,
    /// The message length.
    pub msg_len: usize,
    /// The codeword length.
    pub m: usize,
    /// The discrete Fourier transform implementation.
    pub dft: Dft,
    pub _phantom: PhantomData<F>,
}

impl<F: TwoAdicField, Dft> ReedSolomonZkEncoding<F, Dft> {
    pub const fn new(t: usize, msg_len: usize, m: usize, dft: Dft) -> Self {
        Self {
            t,
            msg_len,
            m,
            dft,
            _phantom: PhantomData,
        }
    }

    /// Retrieve the evaluation point `x` at the given index in the DFT domain.
    pub fn evaluation_point(&self, position: usize) -> F {
        let log2_m = self.m.trailing_zeros() as usize;
        let g = F::two_adic_generator(log2_m);
        g.exp_u64(position as u64)
    }
}

impl<F, Dft> ZkEncoding<F> for ReedSolomonZkEncoding<F, Dft>
where
    F: TwoAdicField,
    Dft: TwoAdicSubgroupDft<F>,
    StandardUniform: Distribution<F>,
{
    type Codeword = RowMajorMatrix<F>;

    fn message_len(&self) -> usize {
        self.msg_len
    }

    fn randomness_len(&self) -> usize {
        self.t
    }

    fn error(&self) -> f64 {
        0.0 // Reed-Solomon encoding provides perfect zero-knowledge (0 error).
    }

    fn encode<R: Rng>(&self, msg: &[F], rng: &mut R) -> Self::Codeword {
        let randomness: Vec<F> = (0..self.t).map(|_| rng.random::<F>()).collect();
        self.encode_with_randomness(msg, &randomness)
    }

    fn simulate<R: Rng>(&self, query_set: &[usize], rng: &mut R) -> Vec<F> {
        assert!(
            query_set.len() <= self.t,
            "Cannot simulate more than t queries"
        );
        // For Reed-Solomon, any <= t evaluations are completely uniformly random.
        (0..query_set.len()).map(|_| rng.random::<F>()).collect()
    }
}

impl<F, Dft> ZkEncodingWithRandomness<F> for ReedSolomonZkEncoding<F, Dft>
where
    F: TwoAdicField,
    Dft: TwoAdicSubgroupDft<F>,
    StandardUniform: Distribution<F>,
{
    fn encode_with_randomness(&self, msg: &[F], randomness: &[F]) -> Self::Codeword {
        assert_eq!(
            msg.len(),
            self.msg_len,
            "Message length must match configured msg_len"
        );
        assert_eq!(
            randomness.len(),
            self.t,
            "Randomness length must match configured t"
        );
        assert!(
            self.msg_len + self.t <= self.m,
            "Message and randomness exceed codeword length"
        );
        let mut coeffs = Vec::with_capacity(self.m);
        coeffs.extend_from_slice(msg);
        coeffs.extend_from_slice(randomness);
        coeffs.resize(self.m, F::ZERO);
        let mat = RowMajorMatrix::new_col(coeffs);
        self.dft.dft_batch(mat).to_row_major_matrix()
    }
}

impl<F, Dft> LinearZkEncoding<F> for ReedSolomonZkEncoding<F, Dft>
where
    F: TwoAdicField,
    Dft: TwoAdicSubgroupDft<F>,
    StandardUniform: Distribution<F>,
{
    /// Evaluates the message segment of the generator polynomial at the given evaluation point.
    /// As defined in Definition 3.17, G_C is decomposed into [G^#_C | G^$_C].
    ///
    /// Mathematically, this corresponds to extracting the row of G^#_C at index i:
    /// G^#[i, ⋅] = (1, x_i, x_i^2, ..., x_i^{ℓ-1})
    /// where ℓ (`msg_len`) is the message length and x_i is the DFT evaluation point.
    fn message_row(&self, position: usize) -> Vec<F> {
        let x = self.evaluation_point(position);
        x.powers().take(self.msg_len).collect()
    }

    /// Evaluates the randomness (mask) segment of the generator polynomial at the given evaluation point.
    /// As defined in Definition 3.17, G_C is decomposed into [G^#_C | G^$_C].
    ///
    /// Mathematically, this corresponds to extracting the row of G^$_C at index i:
    /// G^$[i, ⋅] = (x_i^ℓ, x_i^{ℓ+1}, ..., x_i^{ℓ+t-1})
    /// where ℓ (`msg_len`) is the message length, t (`self.t`) is the random bound,
    /// and x_i is the DFT evaluation point.
    fn randomness_row(&self, position: usize) -> Vec<F> {
        let x = self.evaluation_point(position);
        let mut pow = x.exp_u64(self.msg_len as u64);
        let mut row = Vec::with_capacity(self.t);
        for _ in 0..self.t {
            row.push(pow);
            pow *= x;
        }
        row
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use alloc::vec;
    use p3_baby_bear::BabyBear;
    use p3_dft::Radix2Dit;
    use p3_field::PrimeCharacteristicRing;
    use proptest::prelude::*;
    use rand::SeedableRng;
    use rand_xoshiro::Xoshiro256PlusPlus;

    #[test]
    fn test_zero_randomness_matches_plain_rs() {
        let msg_len = 4;
        let t = 2;
        let m = 8;
        let dft = Radix2Dit::default();
        let encoding = ReedSolomonZkEncoding::<BabyBear, _>::new(t, msg_len, m, dft.clone());

        let msg = vec![
            BabyBear::new(1),
            BabyBear::new(2),
            BabyBear::new(3),
            BabyBear::new(4),
        ];

        // Using encode_with_randomness with ZERO randomness
        let encoded = encoding.encode_with_randomness(&msg, &vec![BabyBear::ZERO; t]);

        // Plain RS encoding (just padding the message with zeros up to m)
        let mut plain_coeffs = msg;
        plain_coeffs.resize(m, BabyBear::ZERO);
        let plain_mat = RowMajorMatrix::new_col(plain_coeffs);
        let plain_encoded = dft.dft_batch(plain_mat).to_row_major_matrix();

        assert_eq!(encoded.values, plain_encoded.values);
    }

    proptest! {
        #[test]
        fn test_simulate_distribution(seed in any::<u64>(), msg_seed in any::<u64>()) {
            let msg_len = 2;
            let t = 2;
            let m = 4;
            let dft = Radix2Dit::default();
            let encoding = ReedSolomonZkEncoding::<BabyBear, _>::new(t, msg_len, m, dft);

            let mut msg_rng = Xoshiro256PlusPlus::seed_from_u64(msg_seed);
            let msg = vec![msg_rng.random::<BabyBear>(), msg_rng.random::<BabyBear>()];

            let mut rng1 = Xoshiro256PlusPlus::seed_from_u64(seed);
            let _encoded = encoding.encode(&msg, &mut rng1);

            let mut rng2 = Xoshiro256PlusPlus::seed_from_u64(seed);
            let simulated = encoding.simulate(&[0, 1], &mut rng2);

            // Verify that the simulation function returns exactly the number
            // of uniform random elements requested for the queried domain.
            // Since any |S| <= t evaluations of a Reed-Solomon codeword with t random masks
            // are perfectly uniform, the simulation outputs exactly match the theoretical distribution.
            assert_eq!(simulated.len(), 2);
        }
    }

    #[test]
    fn test_row_decomposition() {
        let t = 2;
        let msg_len = 2;
        let m = 8;
        let dft = Radix2Dit::default();
        let encoding = ReedSolomonZkEncoding::<BabyBear, _>::new(t, msg_len, m, dft);

        let msg = vec![BabyBear::new(3), BabyBear::new(5)];
        let mut rng = Xoshiro256PlusPlus::seed_from_u64(42);

        // Capture randomness for manual evaluation
        let rand_values: Vec<BabyBear> = (0..t).map(|_| rng.random()).collect();

        // Encode by providing identical randomness
        let encoded = encoding.encode_with_randomness(&msg, &rand_values).values;

        // Verify Enc(f, r)[i] = G#[i] * f + G$[i] * r
        for (i, &enc_val) in encoded.iter().enumerate().take(m) {
            let msg_row = encoding.message_row(i);
            let rand_row = encoding.randomness_row(i);

            let msg_dot: BabyBear = msg_row.iter().zip(&msg).map(|(a, b)| *a * *b).sum();
            let rand_dot: BabyBear = rand_row
                .iter()
                .zip(&rand_values)
                .map(|(a, b)| *a * *b)
                .sum();

            assert_eq!(enc_val, msg_dot + rand_dot);
        }
    }
}
