//! Poseidon1 permutation for Goldilocks.
//!
//! # Overview
//!
//! This module provides the Poseidon1 hash permutation instantiated for the
//! Goldilocks field (p = 2^64 - 2^32 + 1). The public API is a single type
//! alias that transparently dispatches to the best available implementation.
//!
//! # Platform Dispatch
//!
//! On **aarch64**, the type alias resolves to a dual-dispatch wrapper:
//! scalar permutations use NEON-accelerated MDS for full rounds with
//! LLVM-optimized sparse partial rounds, while packed NEON permutations
//! use the fused dual-lane ASM path (w8) or per-lane scalar path (w12).
//!
//! On **all other platforms**, it resolves to the generic Poseidon1
//! implementation with Karatsuba MDS convolution.
//!
//! No `#[cfg]` is needed in calling code.
//!
//! # MDS Matrix
//!
//! The MDS matrix is a **circulant** matrix sourced from the MDS crate.
//! At runtime, it is applied via fast Karatsuba convolution (sub-O(t^2)).
//! During initialization only, it is expanded to dense form for the
//! sparse matrix decomposition of partial rounds.
//!
//! # Round Constants
//!
//! Generated by the Grain LFSR (Poseidon1 paper, Appendix E) with SBOX=0 (x^alpha encoding).

use p3_poseidon1::{
    Poseidon1, Poseidon1Constants, Poseidon1ExternalLayerGeneric, Poseidon1InternalLayerGeneric,
};

use crate::mds::{MATRIX_CIRC_MDS_8_COL, MATRIX_CIRC_MDS_12_COL};
use crate::{Goldilocks, MdsMatrixGoldilocks};

/// S-box degree for Goldilocks Poseidon1.
///
/// The S-box raises each element to this power. The Goldilocks prime
/// factors as `p - 1 = 2^32 * 3 * 5 * 17 * 257 * 65537`. Neither 3 nor 5
/// are coprime to `p - 1`, so the smallest valid exponent is 7.
pub const GOLDILOCKS_S_BOX_DEGREE: u64 = 7;

/// Number of full rounds per half for Goldilocks Poseidon (`RF / 2`).
///
/// The total number of full rounds is `RF = 8` (4 beginning + 4 ending).
/// Follows the Poseidon paper's security analysis (Section 5.4) with a +2 RF margin.
pub const GOLDILOCKS_POSEIDON_HALF_FULL_ROUNDS: usize = 4;

/// Number of partial rounds for Goldilocks Poseidon (width 8).
///
/// Derived from the interpolation bound in the Poseidon paper (Eq. 3):
///
///   R_interp ≥ ⌈min{κ,n}/log_2(α)⌉ + ⌈log_α(t)⌉ − 5
///            = ⌈64/log_2(7)⌉ + ⌈log_7(8)⌉ − 5 = 23 + 2 − 5 = 20
///
/// With the +7.5% security margin (Section 5.4): ⌈1.075 × 20⌉ = 22.
pub const GOLDILOCKS_POSEIDON_PARTIAL_ROUNDS_8: usize = 22;

/// Number of partial rounds for Goldilocks Poseidon (width 12).
///
/// Same interpolation bound as width 8:
///
///   R_interp ≥ ⌈64/log_2(7)⌉ + ⌈log_7(12)⌉ − 5 = 23 + 2 − 5 = 20
///
/// With the +7.5% security margin: ⌈1.075 × 20⌉ = 22.
pub const GOLDILOCKS_POSEIDON_PARTIAL_ROUNDS_12: usize = 22;

/// Generic (non-fused) Poseidon1 permutation for Goldilocks.
///
/// Uses the platform-independent Poseidon1 implementation with Karatsuba
/// MDS convolution. Used directly for widths not supported by the fused
/// type (e.g. 16, 24) and as the non-aarch64 fallback for widths 8 and 12.
pub type Poseidon1GoldilocksGeneric<const WIDTH: usize> = Poseidon1<
    Goldilocks,
    Poseidon1ExternalLayerGeneric<Goldilocks, MdsMatrixGoldilocks, WIDTH>,
    Poseidon1InternalLayerGeneric<Goldilocks, WIDTH>,
    WIDTH,
    GOLDILOCKS_S_BOX_DEGREE,
>;

/// Unified Poseidon1 permutation for Goldilocks.
///
/// On aarch64, resolves to a dual-dispatch wrapper: scalar permutations
/// use NEON MDS for full rounds with sparse partial rounds, packed NEON
/// permutations use fused dual-lane ASM (w8) or per-lane scalar (w12).
///
/// On all other platforms, resolves to the generic implementation with
/// Karatsuba MDS convolution.
///
/// Supports both scalar and packed state representations transparently.
#[cfg(target_arch = "aarch64")]
pub type Poseidon1Goldilocks<const WIDTH: usize> = crate::Poseidon1GoldilocksDispatch<WIDTH>;

/// Unified Poseidon1 permutation for Goldilocks.
///
/// On aarch64, resolves to the fused ASM-optimized implementation that
/// uses inline assembly and dual-lane NEON processing.
///
/// On all other platforms, resolves to the generic implementation with
/// Karatsuba MDS convolution.
///
/// Supports both scalar and packed state representations transparently.
#[cfg(not(target_arch = "aarch64"))]
pub type Poseidon1Goldilocks<const WIDTH: usize> = Poseidon1GoldilocksGeneric<WIDTH>;

/// Full round constants for width-8 Poseidon1 on Goldilocks.
///
/// Generated by the Grain LFSR with parameters:
///     field_type=1, alpha=7 (exp_flag=0), n=64, t=8, R_F=8, R_P=22
///
/// Generated by `poseidon/generate_constants.py --field goldilocks --width 8`.
///
/// Layout: [initial_full (4 rounds), terminal_full (4 rounds)].
pub const GOLDILOCKS_POSEIDON1_FULL_RC_8: [[Goldilocks; 8]; 8] = Goldilocks::new_2d_array([
    // Initial full rounds (4)
    [
        0xdd5743e7f2a5a5d9,
        0xcb3a864e58ada44b,
        0xffa2449ed32f8cdc,
        0x42025f65d6bd13ee,
        0x7889175e25506323,
        0x34b98bb03d24b737,
        0xbdcc535ecc4faa2a,
        0x5b20ad869fc0d033,
    ],
    [
        0xf1dda5b9259dfcb4,
        0x27515210be112d59,
        0x4227d1718c766c3f,
        0x26d333161a5bd794,
        0x49b938957bf4b026,
        0x4a56b5938b213669,
        0x1120426b48c8353d,
        0x6b323c3f10a56cad,
    ],
    [
        0xce57d6245ddca6b2,
        0xb1fc8d402bba1eb1,
        0xb5c5096ca959bd04,
        0x6db55cd306d31f7f,
        0xc49d293a81cb9641,
        0x1ce55a4fe979719f,
        0xa92e60a9d178a4d1,
        0x002cc64973bcfd8c,
    ],
    [
        0xcea721cce82fb11b,
        0xe5b55eb8098ece81,
        0x4e30525c6f1ddd66,
        0x43c6702827070987,
        0xaca68430a7b5762a,
        0x3674238634df9c93,
        0x88cee1c825e33433,
        0xde99ae8d74b57176,
    ],
    // Terminal full rounds (4)
    [
        0xfb1d6bf0ca43221b,
        0x97b0a1b01d6a2955,
        0x08c60bd622952b30,
        0x43f2be0f9e24147c,
        0xfa7268b7d3730f5d,
        0x43a6c419a23983bb,
        0xcd77c1f7b29b113c,
        0xcfa43c9db8eec29f,
    ],
    [
        0xcaaa95a6c7365dec,
        0x0a91193f798f3be0,
        0x1104497652735dc6,
        0x35aecb93663b515e,
        0x8dbc9916065aa858,
        0xada8f7a0266579ed,
        0x524dee7bec1ea789,
        0xa93aee9dd5af9521,
    ],
    [
        0x9d1f1b54750d707e,
        0x7c9feab87096d5dc,
        0xa2e1fb19f9d4261b,
        0xb714deb448de6346,
        0x225d1f0d011c5403,
        0x1549b7f1d28cedc0,
        0xaef3e46f97d43942,
        0x6dfc7ffe0b38bf08,
    ],
    [
        0x7de853fdc542b663,
        0xa68ecc96610657b2,
        0xe88bb5428af289b1,
        0xd7cfa1504c5569f5,
        0x78a9aad0d642d30a,
        0xd68315f2353dce52,
        0x46e56300f86fcfd5,
        0x323d95332b145fd6,
    ],
]);

/// Partial round constants for width-8 Poseidon1 on Goldilocks.
///
/// Generated by the Grain LFSR with parameters:
///     field_type=1, alpha=7 (exp_flag=0), n=64, t=8, R_F=8, R_P=22
///
/// Generated by `poseidon/generate_constants.py --field goldilocks --width 8`.
///
/// Contains only the first element of each partial round row (22 scalars).
pub const GOLDILOCKS_POSEIDON1_PARTIAL_RC_8: [Goldilocks; 22] = Goldilocks::new_array([
    0x488897d85ff51f56,
    0x56ccb62574aaa918,
    0x14a0c2e1d45f03cd,
    0xfdb25aef2c5bae3b,
    0xb3cb23eced349ae4,
    0xceb0735bf00b2c5f,
    0xb1f6b8eee9adb940,
    0x85ffc27171439d9d,
    0x46fa6a6450dd4735,
    0xcc535945b7dbf0f7,
    0xe40cd4f6c5609a27,
    0x287db8630da89c8b,
    0xe839452eb4b8a5e1,
    0x8b7b05225c4e7dad,
    0xc17f55037cf00de9,
    0xe01dd653daf15809,
    0x49d45382e0f21d4a,
    0x42cca18ebeb265c8,
    0xed12a2276dfa1553,
    0x89e779214737c0b7,
    0x854aee2dc1924137,
    0x49884bf25f4ef15d,
]);

/// Full round constants for width-12 Poseidon1 on Goldilocks.
///
/// Generated by the Grain LFSR with parameters:
///     field_type=1, alpha=7 (exp_flag=0), n=64, t=12, R_F=8, R_P=22
///
/// Generated by `poseidon/generate_constants.py --field goldilocks --width 12`.
///
/// Layout: [initial_full (4 rounds), terminal_full (4 rounds)].
pub const GOLDILOCKS_POSEIDON1_FULL_RC_12: [[Goldilocks; 12]; 8] = Goldilocks::new_2d_array([
    // Initial full rounds (4)
    [
        0x13dcf33aba214f46,
        0x30b3b654a1da6d83,
        0x1fc634ada6159b56,
        0x937459964dc03466,
        0xedd2ef2ca7949924,
        0xede9affde0e22f68,
        0x8515b9d6bac9282d,
        0x6b5c07b4e9e900d8,
        0x1ec66368838c8a08,
        0x9042367d80d1fbab,
        0x400283564a3c3799,
        0x4a00be0466bca75e,
    ],
    [
        0x7913beee58e3817f,
        0xf545e88532237d90,
        0x22f8cb8736042005,
        0x6f04990e247a2623,
        0xfe22e87ba37c38cd,
        0xd20e32c85ffe2815,
        0x117227674048fe73,
        0x4e9fb7ea98a6b145,
        0xe0866c232b8af08b,
        0x00bbc77916884964,
        0x7031c0fb990d7116,
        0x240a9e87cf35108f,
    ],
    [
        0x2e6363a5a12244b3,
        0x5e1c3787d1b5011c,
        0x4132660e2a196e8b,
        0x3a013b648d3d4327,
        0xf79839f49888ea43,
        0xfe85658ebafe1439,
        0xb6889825a14240bd,
        0x578453605541382b,
        0x4508cda8f6b63ce9,
        0x9c3ef35848684c91,
        0x0812bde23c87178c,
        0xfe49638f7f722c14,
    ],
    [
        0x8e3f688ce885cbf5,
        0xb8e110acf746a87d,
        0xb4b2e8973a6dabef,
        0x9e714c5da3d462ec,
        0x6438f9033d3d0c15,
        0x24312f7cf1a27199,
        0x23f843bb47acbf71,
        0x9183f11a34be9f01,
        0x839062fbb9d45dbf,
        0x24b56e7e6c2e43fa,
        0xe1683da61c962a72,
        0xa95c63971a19bfa7,
    ],
    // Terminal full rounds (4)
    [
        0x9271d450fc9b4117,
        0xcffeea06b6e3aac1,
        0xfa4a44c748d1cd8e,
        0xe64db01ba569b469,
        0xd31005160e4045fe,
        0x39e0fa013e025f79,
        0xe243be574196a956,
        0x205b2a681e3d2642,
        0x79cae5ad93486bab,
        0xfdf567844e32c295,
        0x331679589bfb7189,
        0xaf06ee32297b89c2,
    ],
    [
        0xa6bcae311e498491,
        0x9d16f52c96ac8b3e,
        0x48a674b59393fa35,
        0x0f9e65da3fde3796,
        0x1e098310fc84578c,
        0x559ae5fab1ae8dad,
        0x56bd4d624078881d,
        0xfd8bbbf8fbe817b5,
        0x82d30695c44df534,
        0x3ec0a97bc41127c5,
        0x1eb8b64adaa22078,
        0x82c45e418d60c983,
    ],
    [
        0xb092280f484d55bf,
        0xcd317c9537697939,
        0xd3be2e352feb79f3,
        0xca6d866539a390e5,
        0xb5efb1a494e55ee6,
        0xfa9013ac89756e9e,
        0xaeb88efd1e981242,
        0x13ee477cdab6e0dc,
        0xce7df902c40da2d3,
        0xf3fbaf0d4e6f5f34,
        0xf96354ada6785f38,
        0x13b5692812406886,
    ],
    [
        0xf03cae030a0f4418,
        0x7d3172887aa98e1a,
        0x8a2c2644f2faf7b9,
        0x80d721abee696d00,
        0x27c8b903a4d68267,
        0xaf0b7b12f90291b8,
        0x00acd08cfdff3817,
        0x4659ee496c634328,
        0xf5b25c10730dbff1,
        0xdde3a153297329c2,
        0x50c0b70d6910a44b,
        0x23c7426af725a6a0,
    ],
]);

/// Partial round constants for width-12 Poseidon1 on Goldilocks.
///
/// Generated by the Grain LFSR with parameters:
///     field_type=1, alpha=7 (exp_flag=0), n=64, t=12, R_F=8, R_P=22
///
/// Generated by `poseidon/generate_constants.py --field goldilocks --width 12`.
///
/// Contains only the first element of each partial round row (22 scalars).
pub const GOLDILOCKS_POSEIDON1_PARTIAL_RC_12: [Goldilocks; 22] = Goldilocks::new_array([
    0x4adf842aa75d4316,
    0x3f36b9fe72ad4e5f,
    0x9717f025e7daf6a5,
    0xac4bb7c627cf7c13,
    0x047d766678f13875,
    0xbfce13201f3f7e6b,
    0x70971fc4e6f85305,
    0xe2a6e06e61fcec9c,
    0xdf58134c134491c2,
    0x1c4bd1e816050a7e,
    0xf8a6cd02e92cdb0b,
    0x4c0f5fc6c0dda3d1,
    0x0a4a11d794be40a2,
    0x6d3fbd3b4a9f1de6,
    0x0d0c371c5b35b850,
    0x2cff3000be1fcd0a,
    0xd5ef60d6f76a42fa,
    0x942069f5d6eece7e,
    0x8b62a5551e9a9797,
    0x4f88cdcdfb791921,
    0xab21b42e0f642307,
    0x587fa39990b62800,
]);

/// Create the default width-8 Poseidon1 permutation for Goldilocks.
///
/// Returns the platform-optimal implementation: dual-dispatch on aarch64
/// (generic for scalar, fused ASM for packed), generic Karatsuba on all
/// other platforms.
#[cfg(target_arch = "aarch64")]
pub fn default_goldilocks_poseidon1_8() -> Poseidon1Goldilocks<8> {
    let constants = Poseidon1Constants {
        rounds_f: 2 * GOLDILOCKS_POSEIDON_HALF_FULL_ROUNDS,
        rounds_p: GOLDILOCKS_POSEIDON_PARTIAL_ROUNDS_8,
        mds_circ_col: MATRIX_CIRC_MDS_8_COL,
        full_round_constants: GOLDILOCKS_POSEIDON1_FULL_RC_8.to_vec(),
        partial_round_constants: GOLDILOCKS_POSEIDON1_PARTIAL_RC_8.to_vec(),
    };
    let (full, partial) = constants.to_optimized();
    let fused = crate::Poseidon1GoldilocksFused::new(&full, &partial);
    crate::Poseidon1GoldilocksDispatch::new(fused, full, partial)
}

/// Create the default width-8 Poseidon1 permutation for Goldilocks.
///
/// Returns the platform-optimal implementation: fused ASM on aarch64,
/// generic Karatsuba on all other platforms.
#[cfg(not(target_arch = "aarch64"))]
pub fn default_goldilocks_poseidon1_8() -> Poseidon1Goldilocks<8> {
    Poseidon1::new(&Poseidon1Constants {
        rounds_f: 2 * GOLDILOCKS_POSEIDON_HALF_FULL_ROUNDS,
        rounds_p: GOLDILOCKS_POSEIDON_PARTIAL_ROUNDS_8,
        mds_circ_col: MATRIX_CIRC_MDS_8_COL,
        full_round_constants: GOLDILOCKS_POSEIDON1_FULL_RC_8.to_vec(),
        partial_round_constants: GOLDILOCKS_POSEIDON1_PARTIAL_RC_8.to_vec(),
    })
}

/// Create the default width-12 Poseidon1 permutation for Goldilocks.
///
/// Returns the platform-optimal implementation: dual-dispatch on aarch64
/// (generic for scalar, fused ASM for packed), generic Karatsuba on all
/// other platforms.
#[cfg(target_arch = "aarch64")]
pub fn default_goldilocks_poseidon1_12() -> Poseidon1Goldilocks<12> {
    let constants = Poseidon1Constants {
        rounds_f: 2 * GOLDILOCKS_POSEIDON_HALF_FULL_ROUNDS,
        rounds_p: GOLDILOCKS_POSEIDON_PARTIAL_ROUNDS_12,
        mds_circ_col: MATRIX_CIRC_MDS_12_COL,
        full_round_constants: GOLDILOCKS_POSEIDON1_FULL_RC_12.to_vec(),
        partial_round_constants: GOLDILOCKS_POSEIDON1_PARTIAL_RC_12.to_vec(),
    };
    let (full, partial) = constants.to_optimized();
    let fused = crate::Poseidon1GoldilocksFused::new(&full, &partial);
    crate::Poseidon1GoldilocksDispatch::new(fused, full, partial)
}

/// Create the default width-12 Poseidon1 permutation for Goldilocks.
///
/// Returns the platform-optimal implementation: fused ASM on aarch64,
/// generic Karatsuba on all other platforms.
#[cfg(not(target_arch = "aarch64"))]
pub fn default_goldilocks_poseidon1_12() -> Poseidon1Goldilocks<12> {
    Poseidon1::new(&Poseidon1Constants {
        rounds_f: 2 * GOLDILOCKS_POSEIDON_HALF_FULL_ROUNDS,
        rounds_p: GOLDILOCKS_POSEIDON_PARTIAL_ROUNDS_12,
        mds_circ_col: MATRIX_CIRC_MDS_12_COL,
        full_round_constants: GOLDILOCKS_POSEIDON1_FULL_RC_12.to_vec(),
        partial_round_constants: GOLDILOCKS_POSEIDON1_PARTIAL_RC_12.to_vec(),
    })
}

#[cfg(test)]
mod tests {
    use p3_symmetric::Permutation;
    use rand::SeedableRng;
    use rand::rngs::SmallRng;

    use super::*;

    type F = Goldilocks;

    /// Known-answer test for width 8 (sequential 0..7 input).
    #[test]
    fn test_poseidon_goldilocks_width_8() {
        let perm = default_goldilocks_poseidon1_8();

        let mut input: [F; 8] = F::new_array([0, 1, 2, 3, 4, 5, 6, 7]);
        perm.permute_mut(&mut input);

        let expected: [F; 8] = F::new_array([
            11153126117091188739,
            9367876523242180035,
            10970566198510919280,
            4291932464886515809,
            10330648916900980499,
            7611656059729716795,
            9509258266284818997,
            17474426264752121404,
        ]);
        assert_eq!(input, expected);
    }

    /// Known-answer test for width 12 (sequential 0..11 input).
    #[test]
    fn test_poseidon_goldilocks_width_12() {
        let perm = default_goldilocks_poseidon1_12();

        let mut input: [F; 12] = F::new_array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]);
        perm.permute_mut(&mut input);

        let expected: [F; 12] = F::new_array([
            11894453562976632264,
            9749618787830132519,
            17643080672090171906,
            13293432833738253032,
            14894677614750348197,
            5957644520194505682,
            17550962642794707178,
            12882156943614641772,
            11315149834689508762,
            9430992202911445529,
            6269945992693421732,
            2269139987008180363,
        ]);
        assert_eq!(input, expected);
    }

    /// Smoke test for width 16 with random constants.
    /// Uses the generic type directly since the fused type only supports 8 and 12.
    #[test]
    fn test_poseidon_goldilocks_width_16() {
        let mut rng = SmallRng::seed_from_u64(1);
        let poseidon = Poseidon1GoldilocksGeneric::<16>::new_from_rng(
            GOLDILOCKS_POSEIDON_HALF_FULL_ROUNDS,
            GOLDILOCKS_POSEIDON_PARTIAL_ROUNDS_8,
            &MdsMatrixGoldilocks,
            &mut rng,
        );
        let input: [F; 16] = rand::RngExt::random(&mut rng);
        let output = poseidon.permute(input);
        assert_ne!(output, input);
    }

    /// Smoke test for width 24 with random constants.
    #[test]
    fn test_poseidon_goldilocks_width_24() {
        let mut rng = SmallRng::seed_from_u64(1);
        let poseidon = Poseidon1GoldilocksGeneric::<24>::new_from_rng(
            GOLDILOCKS_POSEIDON_HALF_FULL_ROUNDS,
            GOLDILOCKS_POSEIDON_PARTIAL_ROUNDS_8,
            &MdsMatrixGoldilocks,
            &mut rng,
        );
        let input: [F; 24] = rand::RngExt::random(&mut rng);
        let output = poseidon.permute(input);
        assert_ne!(output, input);
    }

    #[cfg(all(target_arch = "x86_64", target_feature = "avx512f"))]
    mod avx512 {
        use super::*;
        use crate::PackedGoldilocksAVX512;

        #[test]
        fn test_avx512_poseidon_width_16() {
            let mut rng = SmallRng::seed_from_u64(1);
            let poseidon = Poseidon1GoldilocksGeneric::<16>::new_from_rng(
                GOLDILOCKS_POSEIDON_HALF_FULL_ROUNDS,
                GOLDILOCKS_POSEIDON_PARTIAL_ROUNDS_8,
                &MdsMatrixGoldilocks,
                &mut rng,
            );
            let input: [F; 16] = rand::RngExt::random(&mut rng);

            let mut expected = input;
            poseidon.permute_mut(&mut expected);

            let mut avx512_input = input.map(Into::<PackedGoldilocksAVX512>::into);
            poseidon.permute_mut(&mut avx512_input);

            let avx512_output = avx512_input.map(|x| x.0[0]);
            assert_eq!(avx512_output, expected);
        }

        #[test]
        fn test_avx512_poseidon_width_24() {
            let mut rng = SmallRng::seed_from_u64(1);
            let poseidon = Poseidon1GoldilocksGeneric::<24>::new_from_rng(
                GOLDILOCKS_POSEIDON_HALF_FULL_ROUNDS,
                GOLDILOCKS_POSEIDON_PARTIAL_ROUNDS_8,
                &MdsMatrixGoldilocks,
                &mut rng,
            );
            let input: [F; 24] = rand::RngExt::random(&mut rng);

            let mut expected = input;
            poseidon.permute_mut(&mut expected);

            let mut avx512_input = input.map(Into::<PackedGoldilocksAVX512>::into);
            poseidon.permute_mut(&mut avx512_input);

            let avx512_output = avx512_input.map(|x| x.0[0]);
            assert_eq!(avx512_output, expected);
        }
    }

    #[cfg(all(
        target_arch = "x86_64",
        target_feature = "avx2",
        not(target_feature = "avx512f")
    ))]
    mod avx2 {
        use super::*;
        use crate::PackedGoldilocksAVX2;

        #[test]
        fn test_avx2_poseidon_width_16() {
            let mut rng = SmallRng::seed_from_u64(1);
            let poseidon = Poseidon1GoldilocksGeneric::<16>::new_from_rng(
                GOLDILOCKS_POSEIDON_HALF_FULL_ROUNDS,
                GOLDILOCKS_POSEIDON_PARTIAL_ROUNDS_8,
                &MdsMatrixGoldilocks,
                &mut rng,
            );
            let input: [F; 16] = rand::RngExt::random(&mut rng);

            let mut expected = input;
            poseidon.permute_mut(&mut expected);

            let mut avx2_input = input.map(Into::<PackedGoldilocksAVX2>::into);
            poseidon.permute_mut(&mut avx2_input);

            let avx2_output = avx2_input.map(|x| x.0[0]);
            assert_eq!(avx2_output, expected);
        }

        #[test]
        fn test_avx2_poseidon_width_24() {
            let mut rng = SmallRng::seed_from_u64(1);
            let poseidon = Poseidon1GoldilocksGeneric::<24>::new_from_rng(
                GOLDILOCKS_POSEIDON_HALF_FULL_ROUNDS,
                GOLDILOCKS_POSEIDON_PARTIAL_ROUNDS_8,
                &MdsMatrixGoldilocks,
                &mut rng,
            );
            let input: [F; 24] = rand::RngExt::random(&mut rng);

            let mut expected = input;
            poseidon.permute_mut(&mut expected);

            let mut avx2_input = input.map(Into::<PackedGoldilocksAVX2>::into);
            poseidon.permute_mut(&mut avx2_input);

            let avx2_output = avx2_input.map(|x| x.0[0]);
            assert_eq!(avx2_output, expected);
        }
    }

    #[cfg(target_arch = "aarch64")]
    mod neon {
        use super::*;
        use crate::PackedGoldilocksNeon;

        #[test]
        fn test_neon_poseidon_width_8() {
            let perm = default_goldilocks_poseidon1_8();
            let input: [F; 8] = F::new_array([0, 1, 2, 3, 4, 5, 6, 7]);

            let mut expected = input;
            perm.permute_mut(&mut expected);

            let mut neon_input = input.map(Into::<PackedGoldilocksNeon>::into);
            perm.permute_mut(&mut neon_input);

            let neon_output = neon_input.map(|x| x.0[0]);
            assert_eq!(neon_output, expected);
        }

        #[test]
        fn test_neon_poseidon_width_12() {
            let perm = default_goldilocks_poseidon1_12();
            let input: [F; 12] = F::new_array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]);

            let mut expected = input;
            perm.permute_mut(&mut expected);

            let mut neon_input = input.map(Into::<PackedGoldilocksNeon>::into);
            perm.permute_mut(&mut neon_input);

            let neon_output = neon_input.map(|x| x.0[0]);
            assert_eq!(neon_output, expected);
        }
    }
}
