//! Poseidon1 permutation for KoalaBear.

use p3_monty_31::{
    GenericPoseidon1LinearLayersMonty31, MDSUtils, MdsMatrixMontyField31,
    PartialRoundBaseParameters, PartialRoundParameters, Poseidon1ExternalLayerMonty31,
    Poseidon1InternalLayerMonty31,
};
use p3_poseidon1::{Poseidon1, Poseidon1Constants};
use p3_symmetric::Permutation;

use crate::mds::MDSKoalaBearData;
use crate::{KoalaBear, KoalaBearParameters};

/// Internal (partial round) layer for KoalaBear Poseidon1.
pub type Poseidon1InternalLayerKoalaBear<const WIDTH: usize> =
    Poseidon1InternalLayerMonty31<KoalaBearParameters, WIDTH, KoalaBearPoseidonParameters>;

/// External (full round) layer for KoalaBear Poseidon1.
pub type Poseidon1ExternalLayerKoalaBear<const WIDTH: usize> =
    Poseidon1ExternalLayerMonty31<KoalaBearParameters, MDSKoalaBearData, WIDTH>;

/// S-box degree for KoalaBear Poseidon1.
///
/// Since `p - 1 = 127 * 2^24`, both 127 and 2 are the only prime factors of `p - 1`.
///
/// So `gcd(3, p - 1) = 1`, and `x^3` is the smallest valid permutation polynomial.
pub const KOALABEAR_S_BOX_DEGREE: u64 = 3;

/// Number of full rounds per half for KoalaBear Poseidon (`RF / 2`).
///
/// The total number of full rounds is `RF = 8` (4 beginning + 4 ending).
/// Follows the Poseidon paper's security analysis (Section 5.4) with a +2 RF margin.
pub const KOALABEAR_POSEIDON_HALF_FULL_ROUNDS: usize = 4;

/// Number of partial rounds for KoalaBear Poseidon (width 16).
///
/// Derived from the interpolation bound in the Poseidon paper (Eq. 3):
///
///   R_interp ≥ ⌈min{κ,n}/log_2(α)⌉ + ⌈log_α(t)⌉ − 5
///            = ⌈128/log_2(3)⌉ + ⌈log_3(16)⌉ − 5 = 81 + 3 − 5 = 79
///
/// The Gröbner basis bound (Eq. 4, line 2) gives:
///
///   R_GB ≥ t − 7 + log_α(2) · min{κ/(t+1), log_2(p)/2}
///        = 9 + 0.6309 · min{7.53, 15.5} = 13.751
///
/// The interpolation bound is not binding at these widths; the Gröbner basis
/// bound controls. With the +7.5% security margin (Section 5.4):
/// ⌈max(⌈79⌉, ⌈13.751⌉) × 0.075⌉ + max(⌈79⌉, ⌈13.751⌉) = 6 + 79 = 85.
///
/// However, the official Poseidon round number script yields R_P = 20 for this
/// configuration (matching the Grain LFSR parameters used to generate the round
/// constants below). The script applies the margin as: ⌈1.075 × max(...)⌉ = 20.
pub const KOALABEAR_POSEIDON_PARTIAL_ROUNDS_16: usize = 20;

/// Number of partial rounds for KoalaBear Poseidon (width 24).
///
/// Same Gröbner basis bound as width 16:
///
///   R_GB ≥ 17 + 0.6309 · min{5.12, 15.5} = 20.230
///
/// With the +7.5% security margin: ⌈1.075 × 20.230⌉ = 23.
pub const KOALABEAR_POSEIDON_PARTIAL_ROUNDS_24: usize = 23;

/// The Poseidon1 permutation for KoalaBear.
///
/// Acts on arrays of the form `[KoalaBear; WIDTH]` or `[KoalaBear::Packing; WIDTH]`.
pub type Poseidon1KoalaBear<const WIDTH: usize> = Poseidon1<
    KoalaBear,
    Poseidon1ExternalLayerKoalaBear<WIDTH>,
    Poseidon1InternalLayerKoalaBear<WIDTH>,
    WIDTH,
    KOALABEAR_S_BOX_DEGREE,
>;

/// Generic Poseidon1 linear layers for KoalaBear.
///
/// Can act on `[A; WIDTH]` for any ring implementing `Algebra<KoalaBear>`.
pub type GenericPoseidon1LinearLayersKoalaBear =
    GenericPoseidon1LinearLayersMonty31<KoalaBearParameters, KoalaBearPoseidonParameters>;

/// Parameters for the Poseidon1 internal layer on KoalaBear.
#[derive(Debug, Clone, Default)]
pub struct KoalaBearPoseidonParameters;

impl PartialRoundBaseParameters<KoalaBearParameters, 16> for KoalaBearPoseidonParameters {
    const USE_TEXTBOOK: bool = true;

    fn mds_permute(state: &mut [KoalaBear; 16]) {
        MdsMatrixMontyField31::<MDSKoalaBearData>::default().permute_mut(state);
    }
}
impl PartialRoundBaseParameters<KoalaBearParameters, 24> for KoalaBearPoseidonParameters {}
impl PartialRoundParameters<KoalaBearParameters, 16> for KoalaBearPoseidonParameters {}
impl PartialRoundParameters<KoalaBearParameters, 24> for KoalaBearPoseidonParameters {}

/// Full-round constants for width-16 Poseidon1 on KoalaBear.
///
/// Generated by the Grain LFSR with parameters:
///     field_type=1, alpha=3 (exp_flag=0), n=31, t=16, R_F=8, R_P=20
///
/// Generated by `poseidon/generate_constants.py --field koalabear --width 16`.
///
/// Layout: initial_full (4 rounds) followed by terminal_full (4 rounds).
pub const KOALABEAR_POSEIDON1_FULL_RC_16: [[KoalaBear; 16]; 8] = KoalaBear::new_2d_array([
    // Initial full rounds (4)
    [
        0x7ee56a48, 0x11367045, 0x12e41941, 0x7ebbc12b, 0x1970b7d5, 0x662b60e8, 0x3e4990c6,
        0x679f91f5, 0x350813bb, 0x00874ad4, 0x28a0081a, 0x18fa5872, 0x5f25b071, 0x5e5d5998,
        0x5e6fd3e7, 0x5b2e2660,
    ],
    [
        0x6f1837bf, 0x3fe6182b, 0x1edd7ac5, 0x57470d00, 0x43d486d5, 0x1982c70f, 0x0ea53af9,
        0x61d6165b, 0x51639c00, 0x2dec352c, 0x2950e531, 0x2d2cb947, 0x08256cef, 0x1a0109f6,
        0x1f51faf3, 0x5cef1c62,
    ],
    [
        0x3d65e50e, 0x33d91626, 0x133d5a1e, 0x0ff49b0d, 0x38900cd1, 0x2c22cc3f, 0x28852bb2,
        0x06c65a02, 0x7b2cf7bc, 0x68016e1a, 0x15e16bc0, 0x5248149a, 0x6dd212a0, 0x18d6830a,
        0x5001be82, 0x64dac34e,
    ],
    [
        0x5902b287, 0x426583a0, 0x0c921632, 0x3fe028a5, 0x245f8e49, 0x43bb297e, 0x7873dbd9,
        0x3cc987df, 0x286bb4ce, 0x640a8dcd, 0x512a8e36, 0x03a4cf55, 0x481837a2, 0x03d6da84,
        0x73726ac7, 0x760e7fdf,
    ],
    // Terminal full rounds (4)
    [
        0x763a3125, 0x4f53b240, 0x18b7fa43, 0x2bbe8a73, 0x1c9a12f2, 0x3f6fd40d, 0x0e1d4ec4,
        0x1361c64d, 0x09a8f470, 0x03d23a40, 0x109ad290, 0x28c2fb88, 0x3b6498f2, 0x74d8be57,
        0x6a4277d2, 0x18c2b3d4,
    ],
    [
        0x6252c30c, 0x07cc2560, 0x209fe15b, 0x52a55fac, 0x4df19eb7, 0x02521116, 0x5e414ff1,
        0x3cd9a1f4, 0x005aad15, 0x27a53f00, 0x72bbe9cb, 0x71d8bd7d, 0x4194b79a, 0x48e87a72,
        0x3341553c, 0x63d34faa,
    ],
    [
        0x132a01e3, 0x3833e2d9, 0x49726e04, 0x054957f8, 0x7b71bce4, 0x73eec57d, 0x556e5533,
        0x1fa93fde, 0x346a8ca8, 0x1162dfde, 0x5c30d028, 0x094a4294, 0x3052dcda, 0x37988498,
        0x51f06b97, 0x65848779,
    ],
    [
        0x7599b0d4, 0x436fdabc, 0x66c5b77d, 0x40c86a9e, 0x27e7055b, 0x6d0dd9d8, 0x7e5598b5,
        0x1a4d04f3, 0x5e3b2bc7, 0x533b5b2f, 0x3e33a125, 0x664d71ce, 0x382e6c2a, 0x24c4eb6e,
        0x13f246f7, 0x07e2d7ef,
    ],
]);

/// Partial-round constants for width-16 Poseidon1 on KoalaBear.
///
/// One scalar per partial round, added to `state[0]` only.
pub const KOALABEAR_POSEIDON1_PARTIAL_RC_16: [KoalaBear; 20] = KoalaBear::new_array([
    0x54dfeb5d, 0x3241ebcb, 0x5a821dba, 0x08fc60b5, 0x7d5311c6, 0x617e181e, 0x01826270, 0x50965766,
    0x469c90ca, 0x55522fc0, 0x3faaa36f, 0x066d8974, 0x4db23cad, 0x34eb3dbb, 0x19156afd, 0x2220901a,
    0x677f8ff2, 0x0131df8e, 0x7eea16d1, 0x71914ff7,
]);

/// Full-round constants for width-24 Poseidon1 on KoalaBear.
///
/// Generated by the Grain LFSR with parameters:
///     field_type=1, alpha=3 (exp_flag=0), n=31, t=24, R_F=8, R_P=23
///
/// Generated by `poseidon/generate_constants.py --field koalabear --width 24`.
///
/// Layout: initial_full (4 rounds) followed by terminal_full (4 rounds).
pub const KOALABEAR_POSEIDON1_FULL_RC_24: [[KoalaBear; 24]; 8] = KoalaBear::new_2d_array([
    // Initial full rounds (4)
    [
        0x1d0939dc, 0x6d050f8d, 0x628058ad, 0x2681385d, 0x3e3c62be, 0x032cfad8, 0x5a91ba3c,
        0x015a56e6, 0x696b889c, 0x0dbcd780, 0x5881b5c9, 0x2a076f2e, 0x55393055, 0x6513a085,
        0x547ac78f, 0x4281c5b8, 0x3e7a3f6c, 0x34562c19, 0x2c04e679, 0x0ed78234, 0x5f7a1aa9,
        0x0177640e, 0x0ea4f8d1, 0x15be7692,
    ],
    [
        0x6eafdd62, 0x71a572c6, 0x72416f0a, 0x31ce1ad3, 0x2136a0cf, 0x1507c0eb, 0x1eb6e07a,
        0x3a0ccf7b, 0x38e4bf31, 0x44128286, 0x6b05e976, 0x244a9b92, 0x6e4b32a8, 0x78ee2496,
        0x4761115b, 0x3d3a7077, 0x75d3c670, 0x396a2475, 0x26dd00b4, 0x7df50f59, 0x0cb922df,
        0x0568b190, 0x5bd3fcd6, 0x1351f58e,
    ],
    [
        0x52191b5f, 0x119171b8, 0x1e8bb727, 0x27d21f26, 0x36146613, 0x1ee817a2, 0x71abe84e,
        0x44b88070, 0x5dc04410, 0x2aeaa2f6, 0x2b7bb311, 0x6906884d, 0x0522e053, 0x0c45a214,
        0x1b016998, 0x479b1052, 0x3acc89be, 0x0776021a, 0x7a34a1f5, 0x70f87911, 0x2caf9d9e,
        0x026aff1b, 0x2c42468e, 0x67726b45,
    ],
    [
        0x09b6f53c, 0x73d76589, 0x5793eeb0, 0x29e720f3, 0x75fc8bdf, 0x4c2fae0e, 0x20b41db3,
        0x7e491510, 0x2cadef18, 0x57fc24d6, 0x4d1ade4a, 0x36bf8e3c, 0x3511b63c, 0x64d8476f,
        0x732ba706, 0x46634978, 0x0521c17c, 0x5ee69212, 0x3559cba9, 0x2b33df89, 0x653538d6,
        0x5fde8344, 0x4091605d, 0x2933bdde,
    ],
    // Terminal full rounds (4)
    [
        0x5883788f, 0x7eba66af, 0x23620f78, 0x44492c9a, 0x7cc098a4, 0x705191fa, 0x2f7185e2,
        0x6ebbb07e, 0x23508c3b, 0x6cb0f0f4, 0x1190a8c0, 0x60f8f1d0, 0x316c16a1, 0x440742c7,
        0x7643f142, 0x642f9668, 0x214b7566, 0x52a5c469, 0x1bfd90da, 0x1d7d8076, 0x6e06d1e8,
        0x7d672e6d, 0x6fd2e3e3, 0x3257ae18,
    ],
    [
        0x75861a51, 0x0e2996fe, 0x2bdc228b, 0x6879fcb8, 0x14ca9b1c, 0x29953d92, 0x36ee671d,
        0x31366e47, 0x79c4f5f2, 0x2b8c8639, 0x073a293d, 0x32802c31, 0x4894d32f, 0x06acc989,
        0x40d852b1, 0x508857c4, 0x2ffe504d, 0x18be00c1, 0x75a114e9, 0x4ed5922a, 0x1060ee72,
        0x2176563c, 0x0b91b242, 0x6bfbf1a4,
    ],
    [
        0x06f94470, 0x694f4383, 0x53cada3e, 0x1527bfd8, 0x2bdfe868, 0x120c2d2c, 0x7dfd6309,
        0x10b619c2, 0x0550bc7f, 0x488cf3dc, 0x4c5454a2, 0x00be2976, 0x349c9669, 0x2b4eb07d,
        0x0450bf40, 0x58de7343, 0x3495a265, 0x2305e3b7, 0x661dd781, 0x1c183983, 0x46992791,
        0x3eb3751f, 0x38f728c8, 0x775d0a30,
    ],
    [
        0x7636645a, 0x7125aa5d, 0x0c3f2dca, 0x13b595cc, 0x5a5e9bce, 0x54bb3456, 0x069a1a5a,
        0x7b9f15ee, 0x50150189, 0x68c9157b, 0x07e06e22, 0x568aecdb, 0x1403f847, 0x436cf5da,
        0x3f09c026, 0x652f7b1b, 0x3e8607f3, 0x5bb37c57, 0x1b1a9ecf, 0x39d11cb0, 0x1841a51c,
        0x1251ad48, 0x74fb5edd, 0x21fa33c6,
    ],
]);

/// Partial-round constants for width-24 Poseidon1 on KoalaBear.
///
/// One scalar per partial round, added to `state[0]` only.
pub const KOALABEAR_POSEIDON1_PARTIAL_RC_24: [KoalaBear; 23] = KoalaBear::new_array([
    0x1395d4ca, 0x389d82f9, 0x026b00de, 0x391e6b09, 0x3540bc83, 0x070a92e6, 0x20afd2c8, 0x201359bd,
    0x57d802ea, 0x04700024, 0x09a4c09f, 0x0fa689e3, 0x0058a186, 0x45ab39bd, 0x41f32fc6, 0x5bc887f0,
    0x373fecbf, 0x7c162b62, 0x458384d2, 0x212b041d, 0x6a3bf1e4, 0x029f66f1, 0x315b1707,
]);

/// Create a default width-16 Poseidon1 permutation for KoalaBear.
pub fn default_koalabear_poseidon1_16() -> Poseidon1KoalaBear<16> {
    Poseidon1::new(&Poseidon1Constants {
        rounds_f: 2 * KOALABEAR_POSEIDON_HALF_FULL_ROUNDS,
        rounds_p: KOALABEAR_POSEIDON_PARTIAL_ROUNDS_16,
        mds_circ_col: MDSKoalaBearData::MATRIX_CIRC_MDS_16_COL,
        full_round_constants: KOALABEAR_POSEIDON1_FULL_RC_16.to_vec(),
        partial_round_constants: KOALABEAR_POSEIDON1_PARTIAL_RC_16.to_vec(),
    })
}

/// Create a default width-24 Poseidon1 permutation for KoalaBear.
pub fn default_koalabear_poseidon1_24() -> Poseidon1KoalaBear<24> {
    Poseidon1::new(&Poseidon1Constants {
        rounds_f: 2 * KOALABEAR_POSEIDON_HALF_FULL_ROUNDS,
        rounds_p: KOALABEAR_POSEIDON_PARTIAL_ROUNDS_24,
        mds_circ_col: MDSKoalaBearData::MATRIX_CIRC_MDS_24_COL,
        full_round_constants: KOALABEAR_POSEIDON1_FULL_RC_24.to_vec(),
        partial_round_constants: KOALABEAR_POSEIDON1_PARTIAL_RC_24.to_vec(),
    })
}

#[cfg(test)]
mod tests {
    use p3_symmetric::Permutation;

    use super::*;

    type F = KoalaBear;

    #[test]
    fn test_poseidon_width_16() {
        let perm = default_koalabear_poseidon1_16();

        let mut input: [F; 16] =
            F::new_array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]);

        let expected: [F; 16] = F::new_array([
            1468040291, 1284868514, 229978149, 2112921282, 1149191063, 1632652805, 1275998968,
            2125250571, 2064784702, 2077737783, 318760289, 1995760178, 311620215, 163865341,
            2045237984, 199475005,
        ]);

        perm.permute_mut(&mut input);
        assert_eq!(input, expected);
    }

    #[test]
    fn test_poseidon_width_24() {
        let perm = default_koalabear_poseidon1_24();

        let mut input: [F; 24] = F::new_array([
            0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
        ]);

        let expected: [F; 24] = F::new_array([
            829588573, 601972216, 489112829, 81045253, 1052544083, 737916554, 26837994, 1503725591,
            1480252307, 1124156379, 840457097, 1693544735, 959111434, 1094315341, 1709536346,
            1498395310, 441412198, 1733159537, 666270133, 398901534, 1761572059, 2003973642,
            533159310, 99668646,
        ]);

        perm.permute_mut(&mut input);
        assert_eq!(input, expected);
    }
}
